  ---------------------------------------------------------------------------------
  -- AJUSTES SOLICITADOS -  TVS_SOLICITUD_UNIDAD_DOCUMENTAL
  ---------------------------------------------------------------------------------

ALTER TABLE TVS_SOLICITUD_UD MODIFY (ID_UM VARCHAR2(100 BYTE) DEFAULT NULL) ;

INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (206, 'ME-REC', 'Tipo de Proceso', null, 'A ');

UPDATE TVS_CONSTANTES SET COD_PADRE='ME-REC' WHERE IDE_CONST=22;
UPDATE TVS_CONSTANTES SET COD_PADRE='ME-REC' WHERE IDE_CONST=24;
UPDATE TVS_CONSTANTES SET COD_PADRE='ME-REC' WHERE IDE_CONST=25;
UPDATE TVS_CONSTANTES SET COD_PADRE='ME-REC' WHERE IDE_CONST=28;