  ---------------------------------------------------------------------------------
  -- AJUSTES SOLICITADOS -  FUNCIONARIOS 
  ---------------------------------------------------------------------------------

    -- ELIMINAR LA TABLA DE FUNCIONARIOS
  
	DROP TABLE FUNCIONARIOS;
	
	-- CREAR LAS SIQUIENTES TABLAS 
		
	CREATE TABLE FUNCIONARIOS 
	(
	  IDE_FUNCI NUMBER(18, 0) NOT NULL 
	, COD_TIP_DOC_IDENT VARCHAR2(8 BYTE) NOT NULL 
	, NRO_IDENTIFICACION VARCHAR2(38 BYTE) NOT NULL 
	, NOM_FUNCIONARIO VARCHAR2(100 BYTE) NOT NULL 
	, VAL_APELLIDO1 VARCHAR2(50 BYTE) NOT NULL 
	, VAL_APELLIDO2 VARCHAR2(50 BYTE) DEFAULT NULL 
	, CORR_ELECTRONICO VARCHAR2(100 BYTE) DEFAULT NULL 
	, LOGIN_NAME VARCHAR2(150 BYTE) NOT NULL 
	, ESTADO VARCHAR2(2 CHAR) DEFAULT NULL 
	, FEC_CAMBIO TIMESTAMP(6) 
	, FEC_CREACION TIMESTAMP(6) 
	, COD_USUARIO_CREA VARCHAR2(20 BYTE) 
	) ;

	ALTER TABLE FUNCIONARIOS
	ADD CONSTRAINT FUNCIONARIOS_PK PRIMARY KEY 
	(
	  IDE_FUNCI 
	);
	
	
	CREATE TABLE TVS_ORGA_ADMIN_X_FUNCI_PK 
	(
	  COD_ORGA_ADMI VARCHAR2(8 BYTE) NOT NULL 
	, IDE_FUNCI NUMBER(18, 0) NOT NULL 
	, ESTADO VARCHAR2(2 BYTE) 
	, FEC_CAMBIO TIMESTAMP(6) 
	, FEC_CREACION TIMESTAMP(6) 
	, COD_USUARIO_CREA VARCHAR2(20 BYTE) 
	, CONSTRAINT TVS_ORGA_ADMIN_X_FUNCI_PK_PK PRIMARY KEY 
	  (
		COD_ORGA_ADMI 
	  , IDE_FUNCI 
	  )	  
	); 
	
	-- POC
	
	SELECT * FROM FUNCIONARIOS f INNER JOIN TVS_ORGA_ADMIN_X_FUNCI_PK t on F.IDE_FUNCI =T.IDE_FUNCI
			INNER JOIN TVS_ORGANIGRAMA_ADMINISTRATIVO o on T.COD_ORGA_ADMI =O.COD_ORG 
	WHERE O.VAL_VERSION ='TOP'
	
  ---------------------------------------------------------------------------------
  -- AJUSTES SOLICITADOS -  CONSTANTES 
  ---------------------------------------------------------------------------------
  
  -- ELIMINAR CONSTANTES 
  
  DELETE FROM TVS_CONSTANTES;
  
  -- INSERTAR CONSTANTES
  
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('1', 'TP-VIA', 'Tipo Vía', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('2', 'TP-VIACL', 'Carrera', 'TP-VIA', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('3', 'TP-VIACR', 'Calle', 'TP-VIA', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('4', 'TP-VIADI', 'Diagonal', 'TP-VIA', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('5', 'TP-VIATR', 'Transversal', 'TP-VIA', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('6', 'TP-VIAAV', 'Avenida', 'TP-VIA', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('7', 'EN-CALI', 'En Calidad', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('8', 'EN-CALIN', 'No aplica', 'EN-CALI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('9', 'EN-CALIA', 'Apoderado', 'EN-CALI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('10', 'EN-CALIR', 'Representante legal', 'EN-CALI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('11', 'EN-CALIL', 'Liquidador', 'EN-CALI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('12', 'EN-CALII', 'Interventor', 'EN-CALI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('13', 'EN-CALIO', 'Otros', 'EN-CALI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('14', 'ME-RECE', 'Medio Recepción', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('15', 'ME-RECCE', 'Correo electrónico', 'ME-RECE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('16', 'ME-RECEM', 'Empresa de mensajería', 'ME-RECE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('17', 'ME-RECFS', 'Fax Server', 'ME-RECE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('18', 'ME-RECRC', 'Radicación Contingencia', 'ME-RECE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('19', 'ME-RECSE', 'Sede Electrónica', 'ME-RECE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('20', 'ME-RECVN', 'Ventanilla', 'ME-RECE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('21', 'TP-CMC', 'Tipo Comunicación', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('22', 'EE', 'Comunicación Oficial Externa Recibida', 'TP-CMC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('23', 'EI', 'Comunicación Oficial Interna Recibida', 'TP-CMC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('24', 'TP-PER', 'Tipo Persona', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('25', 'TP-PERPN', 'Persona Natural', 'TP-PER', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('26', 'TP-PERA', 'Anonimo', 'TP-PER', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('27', 'TP-PERPJ', 'Persona Jurídica', 'TP-PER', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('28', 'TP-COMP', 'Complemento Dirección ', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('29', 'TP-COMPA', 'Apartamento', 'TP-COMP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('30', 'TP-COMPC', 'Casa ', 'TP-COMP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('31', 'TP-COMPE', 'Edificio ', 'TP-COMP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('32', 'TP-COMPT', 'Torre', 'TP-COMP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('33', 'TP-AGE', 'Tipo Agente', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('34', 'TP-AGEI', 'Destinatario', 'TP-AGE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('35', 'TP-AGEE', 'Remitente', 'TP-AGE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('36', 'TP-SOP', 'Tipo Soporte', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('37', 'TP-SOPF', 'Físico', 'TP-SOP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('38', 'TP-SOPE', 'Electrónico', 'TP-SOP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('39', 'TP-SOPH', 'Híbrido', 'TP-SOP', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('40', 'TL-DOC', 'Tipología Documento', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('41', 'TL-DOCOF', 'Oficio', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('42', 'TL-DOCT', 'Tutela', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('43', 'TL-DOCDP', 'Derecho de Petición', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('44', 'TL-DOCII', 'Invitación', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('45', 'TL-DOCDM', 'Demanda', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('46', 'TL-DOCF', 'Factura', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('47', 'TL-DOCIE', 'Investigación', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('48', 'TL-DOCDN', 'Denuncia', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('49', 'TL-DOCR', 'Recurso', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('50', 'TL-DOCP', 'PQRSD', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('51', 'TL-DOCA', 'Acta', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('52', 'TL-DOCC', 'Circular', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('53', 'TL-DOCM', 'Memorando', 'TL-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('54', 'ANE', 'Anexos', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('55', 'ANE-CJ', 'Caja', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('56', 'ANE-CD', 'CD', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('57', 'ANE-EXP', 'Expediente', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('58', 'ANE-FL', 'Folleto', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('59', 'ANE-FT', 'Fotografías', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('60', 'ANE-HV', 'Hojas De Vida', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('61', 'ANE-II', 'Invitaciones', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('62', 'ANE-LI', 'Libro', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('63', 'ANE-OF', 'Oficios', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('64', 'ANE-OT', 'Otro', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('65', 'ANE-PR', 'Periódicos', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('66', 'ANE-RV', 'Revista', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('67', 'ANE-SS', 'Sobre sellado', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('68', 'ANE-US', 'USB', 'ANE', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('69', 'ORIEN', 'Orientación', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('70', 'ORIEN-N', 'Norte', 'ORIEN', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('71', 'ORIEN-S', 'Sur', 'ORIEN', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('72', 'BIS', 'BIS', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('73', 'BIS-0', 'BIS', 'BIS', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('74', 'UNID-TI', 'Unidad de Tiempo', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('75', 'UNID-TIH', 'Horas', 'UNID-TI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('76', 'UNID-TID', 'Dias', 'UNID-TI', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('77', 'TP-DES', 'Tipo destinatario', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('78', 'TP-DESP', 'Principal', 'TP-DES', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('79', 'TP-DESC', 'Copia', 'TP-DES', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('80', 'TP-DOC', 'Tipo documento', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('81', 'TP-DOCP', 'Pasaporte', 'TP-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('82', 'TP-DOCT', 'Tarjeta de identidad', 'TP-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('83', 'TP-DOCR', 'Registro civil', 'TP-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('84', 'TP-DOCCE', 'Cedula de extranjería', 'TP-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('85', 'TP-DOCCC', 'Cedula de ciudadanía', 'TP-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('86', 'TP-DOCN', 'Número de Identificación Tributario', 'TP-DOC', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, ESTADO) VALUES ('87', 'PE-CUAD', 'Prefijo Cuadrante', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('88', 'PE-CUAA', 'A', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('89', 'PE-CUAB', 'B', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('90', 'PE-CUAC', 'C', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('91', 'PE-CUADT', 'D', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('92', 'PE-CUAF', 'F', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('93', 'PE-CUAG', 'G', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('94', 'PE-CUAH', 'H', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('95', 'PE-CUAI', 'I', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('96', 'PE-CUAJ', 'J', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('97', 'PE-CUAK', 'K', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('98', 'PE-CUAL', 'L', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('99', 'PE-CUAM', 'M', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('100', 'PE-CUAN', 'N', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('101', 'PE-CUAO', 'O', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('102', 'PE-CUAP', 'P', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('103', 'PE-CUAQ', 'Q', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('104', 'PE-CUAR', 'R', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('105', 'PE-CUAS', 'S', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('106', 'PE-CUAT', 'T', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('107', 'PE-CUAU', 'U', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('108', 'PE-CUAV', 'V', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('109', 'PE-CUAW', 'W', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('110', 'PE-CUAX', 'X', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('111', 'PE-CUAY', 'Y', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('112', 'PE-CUAZ', 'Z', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('113', 'PE-CUANE', 'Ñ', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('114', 'PE-CUAAA', 'AA', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('115', 'PE-CUABB', 'BB', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('116', 'PE-CUACC', 'CC', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('117', 'PE-CUADD', 'DC', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('118', 'PE-CUAFF', 'FF', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('119', 'PE-CUAGG', 'GG', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('120', 'PE-CUAHH', 'HH', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('121', 'PE-CUAII', 'II', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('122', 'PE-CUAJJ', 'JJ', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('123', 'PE-CUAKK', 'KK', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('124', 'PE-CUALL', 'LL', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('125', 'PE-CUAMM', 'MM', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('126', 'PE-CUANN', 'NN', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('127', 'PE-CUAOO', 'OO', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('128', 'PE-CUAPP', 'PP', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('129', 'PE-CUAQQ', 'QQ', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('130', 'PE-CUARR', 'RR', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('131', 'PE-CUASS', 'SS', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('132', 'PE-CUATT', 'TT', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('133', 'PE-CUAUU', 'UU', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('134', 'PE-CUAVV', 'VV', 'PE-CUAD', 'A');
	INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('135', 'PE-CUAWW', 'WW', 'PE-CUAD', 'A');


	  

	
	
  