DELETE FROM TABLE_GENERATOR;
-- ----------------------------
-- Records of TABLE_GENERATOR
-- ----------------------------
INSERT INTO "TABLE_GENERATOR" VALUES ('TVS_ORGANIGRAMA_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('DCT_ASIGNACION_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('DCT_ASIG_ULTIMO_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('TVS_TAREA_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('CM_CARGA_MASIVA_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_PLANILLAS_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_PLAN_AGEN_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_CORRESPONDENCIA_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_REFERIDO_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('PPD_DOCUMENTO_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_AGENTE_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_ANEXO_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('TVS_DATOS_CONTACTO_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('PPD_TRAZ_DOCUMENTO_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('CM_REGISTRO_CARGA_MASIVA_SEQ', '0');
INSERT INTO "TABLE_GENERATOR" VALUES ('TVS_DSERIAL_SEQ', '0');