/*-------------------------------------------------------------------
  --Crear TVS_MUNICIPIO
------------------------------------------------------------------- */
CREATE TABLE TVS_MUNICIPIO 
(
  IDE_MUNIC NUMBER(18, 0) NOT NULL 
, NOMBRE_MUNIC VARCHAR2(64 BYTE) DEFAULT NULL 
, COD_MUNIC VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_DEPAR VARCHAR2(8 BYTE) NOT NULL 
, ESTADO VARCHAR2(2 BYTE) DEFAULT NULL 
, FEC_CAMBIO TIMESTAMP(6) 
, FEC_CREACION TIMESTAMP(6) 
, COD_USUARIO_CREA VARCHAR2(20 BYTE) 
, CONSTRAINT TVS_MUNICIPIO_PK PRIMARY KEY 
  (
    IDE_MUNIC 
  )
  ENABLE 
);
