/*-------------------------------------------------------------------
  --Crear PPD_DOCUMENTO
------------------------------------------------------------------- */


CREATE TABLE PPD_DOCUMENTO 
(
  IDE_PPD_DOCUMENTO NUMBER(18, 0) NOT NULL 
, COD_TIPO_DOC VARCHAR2(8 BYTE) 
, FEC_DOCUMENTO TIMESTAMP(6) NOT NULL 
, COD_ASUNTO VARCHAR2(8 BYTE) NOT NULL 
, NRO_FOLIOS NUMBER(18, 0) 
, NRO_ANEXOS NUMBER(18, 0) 
, COD_EST_DOC VARCHAR2(8 BYTE) 
, FEC_CREACION TIMESTAMP(6) NOT NULL 
, IDE_ECM VARCHAR2(50 BYTE) 
, COD_TIPO_SOPORTE VARCHAR2(8 BYTE) 
, COD_EST_ARCHIVADO VARCHAR2(8 BYTE) 
, IDE_DOCUMENTO NUMBER(18, 0) 
, CONSTRAINT PD_DOCUMENTO_PK PRIMARY KEY 
  (
    IDE_PPD_DOCUMENTO 
  )
  ENABLE 
);

ALTER TABLE PPD_DOCUMENTO
ADD CONSTRAINT PPD_DOCUMENTO_IDE_DOC_FK FOREIGN KEY
(
  IDE_DOCUMENTO 
)
REFERENCES COR_CORRESPONDENCIA
(
  IDE_DOCUMENTO 
)
ENABLE;

