/*-------------------------------------------------------------------
  --Crear TVS_DATOS_CONTACTO
------------------------------------------------------------------- */

CREATE TABLE TVS_DATOS_CONTACTO 
(
  IDE_CONTACTO NUMBER(18, 0) NOT NULL 
, IDE_AGENTE NUMBER(18, 0) NOT NULL 
, NRO_VIA_GENERADORA VARCHAR2(20 BYTE) DEFAULT NULL 
, NRO_PLACA VARCHAR2(10 BYTE) DEFAULT NULL 
, COD_TIPO_VIA VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_PREFIJO_CUADRANT VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_POSTAL VARCHAR2(8 BYTE) DEFAULT NULL 
, DIRECCION VARCHAR2(100 BYTE) DEFAULT NULL 
, CELULAR VARCHAR2(20 BYTE) DEFAULT NULL 
, TEL_FIJO1 VARCHAR2(20 BYTE) DEFAULT NULL 
, TEL_FIJO2 VARCHAR2(20 BYTE) DEFAULT NULL 
, EXTENSION1 VARCHAR2(10 BYTE) DEFAULT NULL 
, EXTENSION2 VARCHAR2(10 BYTE) DEFAULT NULL 
, CORR_ELECTRONICO VARCHAR2(100 BYTE) DEFAULT NULL 
, COD_PAIS VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_DEPARTAMENTO VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_MUNICIPIO VARCHAR2(8 BYTE) DEFAULT NULL 
, PROV_ESTADO VARCHAR2(100 BYTE) DEFAULT NULL 
, CIUDAD VARCHAR2(100 BYTE) DEFAULT NULL 
, CONSTRAINT TVS_DATOS_CONTACTO_PK PRIMARY KEY 
  (
    IDE_CONTACTO 
  )
  ENABLE 
);

ALTER TABLE TVS_DATOS_CONTACTO
ADD CONSTRAINT COR_CONT_IDE_AGE_FK FOREIGN KEY
(
  IDE_AGENTE 
)
REFERENCES COR_AGENTE
(
  IDE_AGENTE 
)
ENABLE;
