/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 192.168.3.244
Source Server Version : 120100
Source Host           : 192.168.3.244:1521
Source Schema         : SGDTEST

Target Server Type    : ORACLE
Target Server Version : 120100
File Encoding         : 65001

Date: 2017-06-07 11:27:23
*/

-- ----------------------------
-- Records of TVS_CONSTANTES
-- ----------------------------

Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('1','TP-VIA','Tipo Vía',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('2','TP-VIACL','Carrera','TP-VIA','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('3','TP-VIACR','Calle','TP-VIA','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('4','TP-VIADI','Diagonal','TP-VIA','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('5','TP-VIATR','Transversal','TP-VIA','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('6','TP-VIAAV','Avenida','TP-VIA','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('7','PE-CUAD','Prefijo Cuadrante',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('8','PE-CUADS','Sur','PE-CUAD','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('9','PE-CUADN','Norte','PE-CUAD','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('10','EN-CALI','En Calidad',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('11','EN-CALIN','No aplica','EN-CALI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('12','EN-CALIA','Apoderado','EN-CALI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('13','EN-CALIR','Representante legal','EN-CALI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('14','EN-CALIL','Liquidador','EN-CALI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('15','EN-CALII','Interventor','EN-CALI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('16','EN-CALIO','Otros','EN-CALI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('17','ME-RECE','Medio Recepción',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('18','ME-RECV','Virtual','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('19','ME-RECE','Escrito','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('20','ME-RECT','Telefónico','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('21','ME-RECCE','Correo electrónico','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('22','ME-RECEM','Empresa de mensajería','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('23','ME-RECFS','Fax Server','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('24','ME-RECPD','Producción Documental','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('25','ME-RECRC','Radicación Contingencia','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('26','ME-RECSE','Sede Electrónica','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('27','ME-RECVN','Ventanilla','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('28','ME-RECCM','Correspondencia Masiva','ME-RECE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('29','TP-CMC','Tipo Comunicación',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('30','EE','Comunicación Oficial Externa Recibida','TP-CMC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('31','EI','Comunicación Oficial Interna Recibida','TP-CMC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('32','TP-PER','Tipo Persona',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('33','TP-PERPN','Persona Natural','TP-PER','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('34','TP-PERPJ','Persona Jurídica','TP-PER','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('35','TP-PEREC','Establecimiento Comercial','TP-PER','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('36','TP-PEREC','Entidad Oficial','TP-PER','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('37','TP-PERA','Anonimo','TP-PER','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('38','TP-REM','Tipo Remitente',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('39','TP-REMI','Interno','TP-REM','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('40','TP-REME','Externo','TP-REM','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('41','TP-AGE','Tipo Agente',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('42','TP-AGEI','Destinatario','TP-AGE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('43','TP-AGEE','Remitente','TP-AGE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('44','TP-SOP','Tipo Soporte',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('45','TP-SOPF','Físico','TP-SOP','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('46','TP-SOPE','Electrónico','TP-SOP','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('47','TP-SOPH','Híbrido','TP-SOP','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('48','TL-DOC','Tipología Documento',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('49','TL-DOCOF','Oficio','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('50','TL-DOCT','Tutela','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('51','TL-DOCDP','Derecho de Petición','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('52','TL-DOCI','Invitación','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('53','TL-DOCD','Demanda','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('54','TL-DOCF','Factura','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('55','TL-DOCI','Investigación','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('56','TL-DOCD','Denuncias','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('57','TL-DOCR','Recursos','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('58','TL-DOCP','PQRSD','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('59','TL-DOCA','Acta','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('60','TL-DOCC','Circular','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('61','TL-DOCM','Memorando','TL-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('62','TCOR','Cortesía',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('63','TCOR-SO','Señor','TCOR','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('64','TCOR-SA','Señora','TCOR','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('65','TCOR-STA','Señorita','TCOR','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('66','TCOR-DO','Doctor','TCOR','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('67','TCOR-DA','Doctora','TCOR','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('68','ANE','Anexos',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('69','ANE-CJ','Caja','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('70','ANE-CD','CD','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('71','ANE-EX','Expediente','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('72','ANE-EX','Expedientes','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('73','ANE-EX','Folleto','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('74','ANE-EX','Fotografías','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('75','ANE-EX','Hojas De Vida','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('76','ANE-EX','Invitaciones','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('77','ANE-EX','Libro','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('78','ANE-EX','Oficios','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('79','ANE-EX','Otro','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('80','ANE-EX','Periódicos','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('81','ANE-EX','Revista','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('82','ANE-EX','Sobre sellado','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('83','ANE-EX','USB','ANE','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('84','ORIEN','Orientación',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('85','ORIEN-N','Norte','ORIEN','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('86','ORIEN-S','Sur','ORIEN','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('87','BIS','BIS',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('88','BIS-0','BIS','BIS','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('89','UNID-TI','Unidad de Tiempo',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('90','UNID-TIH','Horas','UNID-TI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('91','UNID-TID','Dias','UNID-TI','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('92','TP-DES','Tipo destinatario',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('93','TP-DESP','Principal','TP-DES','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('94','TP-DESC','Copia','TP-DES','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('95','TP-DOC','Tipo documento',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('96','TP-DOCP','Pasaporte','TP-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('97','TP-DOCT','Tarjeta de identidad','TP-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('98','TP-DOCR','Registro civil','TP-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('99','TP-DOCCE','Cedula de extranjería','TP-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('100','TP-DOCCC','Cedula de ciudadanía','TP-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('101','TP-DOCN','Número de Identificación Tributario','TP-DOC','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('102','TP-TEL','Tipo Teléfono',null,'A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('103','TP-TELF','Fijo','TP-TEL','A ');
Insert into TVS_CONSTANTES (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values ('104','TP-TELC','Celular','TP-TEL','A ');

-- ----------------------------
-- Indexes structure for table TVS_CONSTANTES
-- ----------------------------

-- ----------------------------
-- Checks structure for table "TVS_CONSTANTES"
-- ----------------------------
ALTER TABLE "TVS_CONSTANTES" ADD CHECK ("IDE_CONST" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "TVS_CONSTANTES"
-- ----------------------------
ALTER TABLE "TVS_CONSTANTES" ADD PRIMARY KEY ("IDE_CONST");











Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (55,'DT-MAG','D.T MAGADALENA','SEDE-ADM','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (56,'DT-MET','D.T META','SEDE-ADM','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (57,'DT-MAR','D.T NARIÑO','SEDE-ADM','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (58,'DT-NOR','D.T NORTE DE SANTANDER','SEDE-ADM','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (59,'DT-PUT','D.T PUTUMAYO','SEDE-ADM','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (60,'DT-CEN','CENTRALES D.T','SEDE-ADM','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (61,'DDT','DESPACHO DIRECCION TERRITORIAL','DT-MAG','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (62,'GAC','GRUPO DE ATENCION AL CIUDADANO','DT-MAG','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (63,'GPIVC','GRUPO DE PREVENCION, INSPECCION, VIGILANCIA, CONTROL','DT-MAG','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (64,'GRCC','GRUPO DE RESOLUCION DE CONFLICTOS-CONCILIACION','DT-MAG','A ');

Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (65,'TRAT-COR','Tratamiento de cortesia',null,'A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (66,'SENOR','SEÑOR','TRAT-COR','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (67,'SENORA','SEÑORA','TRAT-COR','A ');


Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (68,'TIPO-TEL','Tipo de télefono',null,'A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (69,'TEL-MOV','Móvil','TIPO-TEL','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (70,'TEL-FI','Fijo','TIPO-TEL','A ');

INSERT INTO "TABLE_GENERATOR" VALUES ('COR_CORRESPONDENCIA_SEQ', '1');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_AGENTE_SEQ', '1');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_REFERIDO_SEQ', '1');
INSERT INTO "TABLE_GENERATOR" VALUES ('PPD_DOCUMENTO_SEQ', '1');
INSERT INTO "TABLE_GENERATOR" VALUES ('COR_ANEXO_SEQ', '1');
INSERT INTO "TABLE_GENERATOR" VALUES ('TVS_DATOS_CONTACTO_SEQ', '1');
INSERT INTO "TABLE_GENERATOR" VALUES ('PPD_TRAZ_DOCUMENTO_SEQ', '1');



Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (71,'TIPO-VIA','Tipo de via',null,'A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (72,'VIA1','Via 1','TIPO-VIA','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (73,'VIA2','Via 2','TIPO-VIA','A ');

Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (74,'BIS','Bis',null,'A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (75,'BIS1','Bis 1','BIS','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (76,'BIS2','Bis 2','BIS','A ');

Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (77,'ORIENT','Orientacion',null,'A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (78,'ORIEN1','Orientacion 1','ORIENT','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (79,'ORIEN2','Orientacion 2','ORIENT','A ');

Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (80,'PREFI-CU','Orientacion',null,'A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (81,'PREF1','Prefijo 1','PREFI-CU','A ');
Insert into "TVS_CONSTANTES" (IDE_CONST,CODIGO,NOMBRE,COD_PADRE,ESTADO) values (82,'PREF2','Prefijo 2','PREFI-CU','A ');
