/*-------------------------------------------------------------------
  --Crear TVS_DSERIAL
------------------------------------------------------------------- */

CREATE TABLE TVS_DSERIAL 
(
  IDE_SERIAL NUMBER(18, 0) NOT NULL 
, COD_SEDE VARCHAR2(255 BYTE) NOT NULL 
, COD_GRUPO VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_DEPENDENCIA VARCHAR2(255 BYTE) DEFAULT NULL 
, COD_CMC VARCHAR2(8 BYTE) DEFAULT NULL 
, VAL_ANO VARCHAR2(8 BYTE) NOT NULL 
, COD_FUNC_RADICA VARCHAR2(8 BYTE) DEFAULT NULL 
, FEC_CREA TIMESTAMP(6) DEFAULT NULL 
, IND_TIPO_SERIAL CHAR(2 BYTE) DEFAULT NULL 
, VAL_CONSECUTIVO_RAD VARCHAR2(8 BYTE) DEFAULT NULL 
, VAL_CONSECUTIVO_PL VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_TIP_CONSECUTIVO VARCHAR2(8 BYTE) DEFAULT NULL 
, VAL_SERIAL_RAD VARCHAR2(32 BYTE) 
, VAL_SERIAL_PL VARCHAR2(32 BYTE) 
, CONSTRAINT TVS_DSERIAL_PK PRIMARY KEY 
  (
    IDE_SERIAL 
  )
  ENABLE 
);
