/*-------------------------------------------------------------------
  --Crear TVS_DEPARTAMENTO
------------------------------------------------------------------- */

CREATE TABLE TVS_DEPARTAMENTO 
(
  IDE_DEPAR NUMBER(18, 0) NOT NULL 
, NOMBRE_DEPAR VARCHAR2(64 BYTE) DEFAULT NULL 
, COD_DEPAR VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_PAIS VARCHAR2(8 BYTE) DEFAULT NULL 
, ESTADO CHAR(2 BYTE) DEFAULT NULL 
, FEC_CAMBIO TIMESTAMP(6) DEFAULT SYSDATE 
, FEC_CREACION TIMESTAMP(6) DEFAULT SYSDATE 
, COD_USUARIO_CREA VARCHAR2(20 BYTE) DEFAULT NULL 
, CONSTRAINT TVS_DEPARTAMENTO_PK PRIMARY KEY 
  (
    IDE_DEPAR 
  )
  ENABLE 
);