/*-------------------------------------------------------------------
  --Crear DCT_ASIGNACION
------------------------------------------------------------------- */
CREATE TABLE DCT_ASIGNACION 
(
  IDE_ASIGNACION NUMBER(18, 0) NOT NULL 
, FEC_ASIGNACION TIMESTAMP(6) NOT NULL 
, IDE_DOCUMENTO NUMBER(18, 0) NOT NULL 
, IDE_AGENTE NUMBER(18, 0) DEFAULT NULL 
, IDE_FUNCI NUMBER(18, 0) DEFAULT NULL 
, COD_DEPENDENCIA VARCHAR2(32 BYTE) DEFAULT NULL 
, COD_TIP_ASIGNACION VARCHAR2(8 BYTE) NOT NULL 
, OBSERVACIONES VARCHAR2(500 BYTE) DEFAULT NULL 
, COD_TIP_CAUSAL VARCHAR2(12 BYTE) DEFAULT NULL 
, IDE_USUARIO_CREO VARCHAR2(18 BYTE) NOT NULL 
, FEC_CREO TIMESTAMP(6) NOT NULL 
, COD_TIP_PROCESO VARCHAR2(8 BYTE) DEFAULT NULL 
, CONSTRAINT DCT_ASIGNACION_PK PRIMARY KEY 
  (
    IDE_ASIGNACION 
  )
  ENABLE 
);

ALTER TABLE DCT_ASIGNACION
ADD CONSTRAINT DCT_ASIGNACION_IDE_AGENTE_FK FOREIGN KEY
(
  IDE_AGENTE 
)
REFERENCES COR_AGENTE
(
  IDE_AGENTE 
)
ENABLE;

ALTER TABLE DCT_ASIGNACION
ADD CONSTRAINT DCT_ASIGNACION_IDE_DOC_FK FOREIGN KEY
(
  IDE_DOCUMENTO 
)
REFERENCES COR_CORRESPONDENCIA
(
  IDE_DOCUMENTO 
)
ENABLE;

