/*-------------------------------------------------------------------
  --Crear FUNCIONARIOS
------------------------------------------------------------------- */
CREATE TABLE FUNCIONARIOS 
(
  IDE_FUNCI NUMBER(18, 0) NOT NULL 
, COD_TIP_DOC_IDENT VARCHAR2(8 BYTE) NOT NULL 
, NRO_IDENTIFICACION VARCHAR2(38 BYTE) NOT NULL 
, NOM_FUNCIONARIO VARCHAR2(100 BYTE) NOT NULL 
, VAL_APELLIDO1 VARCHAR2(50 BYTE) NOT NULL 
, VAL_APELLIDO2 VARCHAR2(50 BYTE) DEFAULT NULL 
, COD_CARGO VARCHAR2(8 BYTE) NOT NULL 
, CORR_ELECTRONICO VARCHAR2(100 BYTE) DEFAULT NULL 
, COD_ORGA_ADMI VARCHAR2(8 BYTE) NOT NULL 
, LOGIN_NAME VARCHAR2(150 BYTE) NOT NULL 
, ESTADO VARCHAR2(2 CHAR) DEFAULT NULL 
, CONSTRAINT FUNCIONARIO_PK PRIMARY KEY 
  (
    IDE_FUNCI 
  )
  ENABLE 
);
