/*-------------------------------------------------------------------
  --Crear COR_PLAN_AGEN
------------------------------------------------------------------- */
CREATE TABLE COR_PLAN_AGEN 
(
  IDE_PLAN_AGEN NUMBER(18, 0) NOT NULL 
, IDE_PLANILLA NUMBER(18, 0) NOT NULL 
, IDE_AGENTE NUMBER(18, 0) NOT NULL 
, IDE_DOCUMENTO NUMBER(18, 0) NOT NULL 
, ESTADO VARCHAR2(8 BYTE) NOT NULL 
, VAR_PESO VARCHAR2(50 CHAR) DEFAULT NULL 
, VAR_VALOR VARCHAR2(250 BYTE) DEFAULT NULL 
, VAR_NUMERO_GUIA VARCHAR2(250 BYTE) DEFAULT NULL 
, FEC_OBSERVACION TIMESTAMP(6) DEFAULT NULL 
, COD_NUEVA_SEDE VARCHAR2(32 BYTE) DEFAULT NULL 
, COD_NUEVA_DEPEN VARCHAR2(32 BYTE) DEFAULT NULL 
, OBSERVACIONES VARCHAR2(500 BYTE) DEFAULT NULL 
, COD_CAU_DEVO VARCHAR2(8 BYTE) DEFAULT NULL 
, FEC_CARGUE_PLA TIMESTAMP(6) DEFAULT NULL 
, CONSTRAINT PK_COR_PLAN_AGEN PRIMARY KEY 
  (
    IDE_PLAN_AGEN 
  )
  ENABLE 
); 

ALTER TABLE COR_PLAN_AGEN
ADD CONSTRAINT COR_PLAN_AGEN_IDE_DOC_FK FOREIGN KEY
(
  IDE_DOCUMENTO 
)
REFERENCES COR_CORRESPONDENCIA
(
  IDE_DOCUMENTO 
)
ENABLE;

ALTER TABLE COR_PLAN_AGEN
ADD CONSTRAINT COR_PLAN_AGEN_IDE_PLANI_FK FOREIGN KEY
(
  IDE_PLANILLA 
)
REFERENCES COR_PLANILLAS
(
  IDE_PLANILLA 
)
ENABLE;

ALTER TABLE COR_PLAN_AGEN
ADD CONSTRAINT COR_PLAN_IDE_AGE_FK FOREIGN KEY
(
  IDE_AGENTE 
)
REFERENCES COR_AGENTE
(
  IDE_AGENTE 
)
ENABLE;
