/*-------------------------------------------------------------------
  --Crear COR_AGENTE
------------------------------------------------------------------- */
CREATE TABLE COR_AGENTE 
(
  IDE_AGENTE NUMBER(18, 0) NOT NULL 
, IDE_DOCUMENTO NUMBER(18, 0) 
, COD_TIPO_REMITE VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_TIPO_PERS VARCHAR2(8 BYTE) DEFAULT NULL 
, NOMBRE VARCHAR2(100 BYTE) DEFAULT NULL 
, NRO_DOCUMENTO_IDEN VARCHAR2(100 BYTE) DEFAULT NULL 
, RAZON_SOCIAL VARCHAR2(150 BYTE) DEFAULT NULL 
, NIT VARCHAR2(16 BYTE) DEFAULT NULL 
, COD_CORTESIA VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_CARGO VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_EN_CALIDAD VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_TIP_DOC_IDENT VARCHAR2(8 BYTE) DEFAULT NULL 
, NRO_DOCU_IDENTIDAD VARCHAR2(250 BYTE) DEFAULT NULL 
, COD_SEDE VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_DEPENDENCIA VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_FUNC_REMITE VARCHAR2(8 BYTE) DEFAULT NULL 
, COD_ESTADO VARCHAR2(8 BYTE) DEFAULT NULL 
, FEC_ASIGNACION VARCHAR2(200 BYTE) DEFAULT NULL 
, IDE_CONTACTO NUMBER(18, 0) DEFAULT NULL 
, COD_TIP_AGENT VARCHAR2(8 BYTE) DEFAULT NULL 
, IND_ORIGINAL VARCHAR2(20 BYTE) 
, CONSTRAINT COR_AGENTE_PK PRIMARY KEY 
  (
    IDE_AGENTE 
  )
  ENABLE 
) ;

ALTER TABLE COR_AGENTE
ADD CONSTRAINT COR_AGENTE_IDE_DOC_FK FOREIGN KEY
(
  IDE_DOCUMENTO 
)
REFERENCES COR_CORRESPONDENCIA
(
  IDE_DOCUMENTO 
)
ENABLE;
