/*-------------------------------------------------------------------
  --Crear COR_REFERIDO
------------------------------------------------------------------- */

CREATE TABLE COR_REFERIDO 
(
  IDE_REFERIDO NUMBER(18, 0) NOT NULL 
, IDE_DOCUMENTO NUMBER(18, 0) DEFAULT NULL 
, NRO_RAD_REF VARCHAR2(32 BYTE) DEFAULT NULL 
, CONSTRAINT PK_COR_REFERIDO PRIMARY KEY 
  (
    IDE_REFERIDO 
  )
  ENABLE 
);

ALTER TABLE COR_REFERIDO
ADD CONSTRAINT COR_REFERIDO_IDE_DOC_FK FOREIGN KEY
(
  IDE_DOCUMENTO 
)
REFERENCES COR_CORRESPONDENCIA
(
  IDE_DOCUMENTO 
)
ENABLE;
