/*-------------------------------------------------------------------
  --Crear PPD_TRAZ_DOCUMENTO
------------------------------------------------------------------- */

CREATE TABLE PPD_TRAZ_DOCUMENTO 
(
  IDE_TRAZ_DOCUMENTO NUMBER(18, 0) NOT NULL 
, IDE_PPD_DOCUMENTO NUMBER(18, 0) NOT NULL 
, FEC_TRAZ_DOCUMENTO TIMESTAMP(6) NOT NULL 
, OBSERVACION VARCHAR2(500 BYTE) 
, IDE_FUNCI NUMBER(18, 0) 
, COD_ESTADO VARCHAR2(8 BYTE) 
, IDE_DOCUMENTO NUMBER(18, 0) 
, COD_ORGA_ADMIN VARCHAR2(32 BYTE) 
, CONSTRAINT PPD_TRAZ_DOCUMENTO_PK PRIMARY KEY 
  (
    IDE_TRAZ_DOCUMENTO 
  )
  ENABLE 
);

ALTER TABLE PPD_TRAZ_DOCUMENTO
ADD CONSTRAINT PPD_TRAZ_DOC_IDE_PPD_FK FOREIGN KEY
(
  IDE_PPD_DOCUMENTO 
)
REFERENCES PPD_DOCUMENTO
(
  IDE_PPD_DOCUMENTO 
)
ENABLE;
