export interface CorrespondenciaDTO {
  ideDocumento: number;
  descripcion: string;
  tiempoRespuesta: string;
  codUnidadTiempo: string;
  descUnidadTiempo?: string;
  codMedioRecepcion: string;
  descMedioRecepcion?: string;
  fecRadicado: string;
  fecDocumento: string;
  nroRadicado: string;
  codTipoDoc: string;
  codTipoCmc: string;
  descTipoCmc?: string;
  ideInstancia: string;
  reqDistFisica: string;
  codFuncRadica: number;
  descFuncRadica?: string;
  codSede: string;
  descSede?: string;
  codDependencia: string;
  descDependencia?: string;
  reqDigita: string;
  codEmpMsj: string;
  distribuido?:number;
  nroGuia: string;
  fecVenGestion: string;
  codEstado: string;
  descEstado?: string;
  inicioConteo: string;
  codClaseEnvio:string;
  descClaseEnvio?: string;
  codModalidadEnvio:string;
  descModalidadEnvio?: string;
  radicadoPadre?:string;
  abreviatura?:string;
  adjuntarDocumento ? :string;
  reqDistElectronica?:string;
}
