
package co.com.foundation.soaint.documentmanager.integration.client.ecmintegration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenerarEstructuraWS", targetNamespace = "http://co.com.soaint.ecm.integration.service.ws", wsdlLocation = "http://192.168.1.23:28080/ecm-integration-services/GenerarEstructuraWS?wsdl")
public class GenerarEstructuraWS_Service
    extends Service
{

    private final static URL GENERARESTRUCTURAWS_WSDL_LOCATION;
    private final static WebServiceException GENERARESTRUCTURAWS_EXCEPTION;
    private final static QName GENERARESTRUCTURAWS_QNAME = new QName("http://co.com.soaint.ecm.integration.service.ws", "GenerarEstructuraWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.23:28080/ecm-integration-services/GenerarEstructuraWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERARESTRUCTURAWS_WSDL_LOCATION = url;
        GENERARESTRUCTURAWS_EXCEPTION = e;
    }

    public GenerarEstructuraWS_Service() {
        super(__getWsdlLocation(), GENERARESTRUCTURAWS_QNAME);
    }

    public GenerarEstructuraWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERARESTRUCTURAWS_QNAME, features);
    }

    public GenerarEstructuraWS_Service(URL wsdlLocation) {
        super(wsdlLocation, GENERARESTRUCTURAWS_QNAME);
    }

    public GenerarEstructuraWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERARESTRUCTURAWS_QNAME, features);
    }

    public GenerarEstructuraWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerarEstructuraWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenerarEstructuraWS
     */
    @WebEndpoint(name = "GenerarEstructuraWSPort")
    public GenerarEstructuraWS getGenerarEstructuraWSPort() {
        return super.getPort(new QName("http://co.com.soaint.ecm.integration.service.ws", "GenerarEstructuraWSPort"), GenerarEstructuraWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenerarEstructuraWS
     */
    @WebEndpoint(name = "GenerarEstructuraWSPort")
    public GenerarEstructuraWS getGenerarEstructuraWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://co.com.soaint.ecm.integration.service.ws", "GenerarEstructuraWSPort"), GenerarEstructuraWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERARESTRUCTURAWS_EXCEPTION!= null) {
            throw GENERARESTRUCTURAWS_EXCEPTION;
        }
        return GENERARESTRUCTURAWS_WSDL_LOCATION;
    }

}
