
package co.com.foundation.soaint.documentmanager.integration.client.organigrama;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionarOrganigramaAdministrativoWS", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", wsdlLocation = "http://192.168.1.152:28080/correspondencia-business-services/GestionarOrganigramaAdministrativoWS?wsdl")
public class GestionarOrganigramaAdministrativoWS_Service
    extends Service
{

    private final static URL GESTIONARORGANIGRAMAADMINISTRATIVOWS_WSDL_LOCATION;
    private final static WebServiceException GESTIONARORGANIGRAMAADMINISTRATIVOWS_EXCEPTION;
    private final static QName GESTIONARORGANIGRAMAADMINISTRATIVOWS_QNAME = new QName("http://co.com.soaint.sgd.correspondencia.service", "GestionarOrganigramaAdministrativoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.152:28080/correspondencia-business-services/GestionarOrganigramaAdministrativoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONARORGANIGRAMAADMINISTRATIVOWS_WSDL_LOCATION = url;
        GESTIONARORGANIGRAMAADMINISTRATIVOWS_EXCEPTION = e;
    }

    public GestionarOrganigramaAdministrativoWS_Service() {
        super(__getWsdlLocation(), GESTIONARORGANIGRAMAADMINISTRATIVOWS_QNAME);
    }

    public GestionarOrganigramaAdministrativoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONARORGANIGRAMAADMINISTRATIVOWS_QNAME, features);
    }

    public GestionarOrganigramaAdministrativoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, GESTIONARORGANIGRAMAADMINISTRATIVOWS_QNAME);
    }

    public GestionarOrganigramaAdministrativoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONARORGANIGRAMAADMINISTRATIVOWS_QNAME, features);
    }

    public GestionarOrganigramaAdministrativoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionarOrganigramaAdministrativoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionarOrganigramaAdministrativoWS
     */
    @WebEndpoint(name = "GestionarOrganigramaAdministrativoWSPort")
    public GestionarOrganigramaAdministrativoWS getGestionarOrganigramaAdministrativoWSPort() {
        return super.getPort(new QName("http://co.com.soaint.sgd.correspondencia.service", "GestionarOrganigramaAdministrativoWSPort"), GestionarOrganigramaAdministrativoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionarOrganigramaAdministrativoWS
     */
    @WebEndpoint(name = "GestionarOrganigramaAdministrativoWSPort")
    public GestionarOrganigramaAdministrativoWS getGestionarOrganigramaAdministrativoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://co.com.soaint.sgd.correspondencia.service", "GestionarOrganigramaAdministrativoWSPort"), GestionarOrganigramaAdministrativoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONARORGANIGRAMAADMINISTRATIVOWS_EXCEPTION!= null) {
            throw GESTIONARORGANIGRAMAADMINISTRATIVOWS_EXCEPTION;
        }
        return GESTIONARORGANIGRAMAADMINISTRATIVOWS_WSDL_LOCATION;
    }

}
