 -------------------------------------------------------------------
  --Crear CM_REGISTRO_CARGA_MASIVA
  -------------------------------------------------------------------
  CREATE TABLE CM_REGISTRO_CARGA_MASIVA
( 
	ID NUMERIC NOT NULL,
	CARGA_MASIVA_ID NUMERIC,
	CONTENIDO NVARCHAR(1000),
	ESTADO NVARCHAR(25),
	MENSAJES NVARCHAR(1000)
);
ALTER TABLE CM_REGISTRO_CARGA_MASIVA ADD CONSTRAINT CM_REGISTRO_CARGA_MASIVA_PK
	PRIMARY KEY (ID);
ALTER TABLE CM_REGISTRO_CARGA_MASIVA ADD CONSTRAINT SYS_C0011047
	FOREIGN KEY (CARGA_MASIVA_ID)
		REFERENCES CM_CARGA_MASIVA (ID);
		
		
Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('CM_REGISTRO_CARGA_MASIVA_SEQ','1');