-------------------------------------------------------------------
  --Crear ADM_SUBSERIE
  ------------------------------------------------------------------- 
  CREATE TABLE ADM_SUBSERIE
( 
	IDE_SUBSERIE NUMERIC(19) NOT NULL,
	ACT_ADMINISTRATIVO NVARCHAR(1020) NOT NULL,
	CAR_ADMINISTRATIVA NUMERIC(10),
	CAR_LEGAL NUMERIC(10),
	CAR_TECNICA NUMERIC(10),
	COD_SUBSERIE NVARCHAR(1020) NOT NULL,
	EST_SUBSERIE NUMERIC(5) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	FUE_BIBLIOGRAFICA NVARCHAR(1020),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_SUBSERIE NVARCHAR(1020) NOT NULL,
	NOT_ALCANCE NVARCHAR(1020),
	IDE_MOT_CREACION NUMERIC(19) NOT NULL,
	IDE_SERIE NUMERIC(19)
)

ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_PK
	PRIMARY KEY (IDE_SUBSERIE)

ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE)

ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_MOCR_FK
	FOREIGN KEY (IDE_MOT_CREACION)
		REFERENCES ADM_MOT_CREACION (IDE_MOT_CREACION)

CREATE INDEX X_SUBS_MOCR ON ADM_SUBSERIE
(
	IDE_MOT_CREACION
)

CREATE INDEX X_SUBS_SERI ON ADM_SUBSERIE
(
	IDE_SERIE
)
  
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_SUBSERIE_SEQ','1');