USE docmanager
GO

-------------------------------------------------------------------
  --Crear ADM_MOT_CREACION
  -------------------------------------------------------------------
  CREATE TABLE ADM_MOT_CREACION
( 
	IDE_MOT_CREACION NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_MOT_CREACION NVARCHAR(1020) NOT NULL
)

ALTER TABLE ADM_MOT_CREACION ADD CONSTRAINT MOCR_PK
	PRIMARY KEY (IDE_MOT_CREACION)

  
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('1','26/11/14',null,null,null,null,null,'Nuevas Funciones');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('2','26/11/14',null,null,null,null,null,'Reestructuracion');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('3','26/11/14',null,null,null,null,null,'Fusion de Dependencias');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('4','30/06/15',null,null,null,null,null,'Cambio de Funciones entre Dependencias');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('5','26/11/14',null,null,null,null,null,'Normatividad');

  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_MOTIVODOC_SEQ','6');