  -------------------------------------------------------------------
  --Crear ADM_SER_SUBSER_TPG
  -------------------------------------------------------------------
  CREATE TABLE ADM_SER_SUBSER_TPG
( 
	IDE_SERIE NUMERIC(19) NOT NULL,
	IDE_TPG_DOC NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	IDE_SUBSERIE NUMERIC(19),
	IDE_REL_SST NUMERIC(19) NOT NULL
);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_PK
	PRIMARY KEY (IDE_REL_SST);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SUBS_FK
	FOREIGN KEY (IDE_SUBSERIE)
		REFERENCES ADM_SUBSERIE (IDE_SUBSERIE);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_TPDO_FK
	FOREIGN KEY (IDE_TPG_DOC)
		REFERENCES ADM_TPG_DOC (IDE_TPG_DOC);

  
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_SER_SUBSER_TPG_SEQ','1');