 -------------------------------------------------------------------
  --Crear ADM_CCD
  -------------------------------------------------------------------  
  CREATE TABLE ADM_CCD
( 
	IDE_CCD NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5, 0),
	IDE_OFC_PROD NVARCHAR(20) NOT NULL,
	IDE_SERIE NUMERIC(19) NOT NULL,
	IDE_SUBSERIE NUMERIC(19),
	IDE_UNI_AMT NVARCHAR(20) NOT NULL,
	EST_CCD NUMERIC(5),
	VAL_VERSION NVARCHAR(6)
)

ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_PK
	PRIMARY KEY (IDE_CCD)

ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE)

ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_SUBS_FK
	FOREIGN KEY (IDE_SUBSERIE)
		REFERENCES ADM_SUBSERIE (IDE_SUBSERIE)

CREATE INDEX X_CCDS_ORGA ON ADM_CCD
(
	IDE_OFC_PROD
)

CREATE INDEX X_CCDS_ORGA1 ON ADM_CCD
(
	IDE_UNI_AMT
)

CREATE INDEX X_CCDS_SERI ON ADM_CCD
(
	IDE_SERIE
)

CREATE INDEX X_CCDS_SUBS ON ADM_CCD
(
	IDE_SUBSERIE
)

  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_CCD_SEQ','1');