USE docmanager
GO


-------------------------------------------------------------------
--Crear ADM_DIS_FINAL
-------------------------------------------------------------------
CREATE TABLE ADM_DIS_FINAL
( 
	IDE_DIS_FINAL NUMERIC(18) NOT NULL,
	NOM_DIS_FINAL NVARCHAR(100) NOT NULL,
	DES_DIS_FINAL NVARCHAR(100),
	STA_DIS_FINAL NVARCHAR(2),
	IDE_USUARIO_CAMBIO NUMERIC(10),
	FEC_CAMBIO DATETIME2(6),
	NIV_LECTURA NUMERIC(1),
	NIV_ESCRITURA NUMERIC(1),
	IDE_UUID CHAR(32),
	FEC_CREACION DATETIME2(6)
)

ALTER TABLE ADM_DIS_FINAL ADD CONSTRAINT ADM_DIS_FINAL_PK
	PRIMARY KEY (IDE_DIS_FINAL)


  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_DISFINAL_SEQ','1');