USE docmanager
GO

	-------------------------------------------------------------------
  --Crear ADM_SOPORTE
  -------------------------------------------------------------------
  CREATE TABLE ADM_SOPORTE
( 
	IDE_SOPORTE NUMERIC(19) NOT NULL,
	DES_SOPORTE NVARCHAR(1020) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_SOPORTE NVARCHAR(1020) NOT NULL
)

ALTER TABLE ADM_SOPORTE ADD CONSTRAINT SOPO_PK
	PRIMARY KEY (IDE_SOPORTE)

Insert into ADM_SOPORTE (IDE_SOPORTE,DES_SOPORTE,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_SOPORTE) values ('1','Soporte Físico',null,'25/01/16',null,null,null,null,'Físico');
Insert into ADM_SOPORTE (IDE_SOPORTE,DES_SOPORTE,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_SOPORTE) values ('2','Soporte Electrónico',null,'25/01/16',null,null,null,null,'Electrónico');
Insert into ADM_SOPORTE (IDE_SOPORTE,DES_SOPORTE,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_SOPORTE) values ('3','Soporte Híbrido',null,'25/01/16',null,null,null,null,'Físico y Electrónico');
