USE docmanager
GO


-------------------------------------------------------------------
--Crear ADM_DIS_FINAL
-------------------------------------------------------------------
CREATE TABLE ADM_DIS_FINAL
( 
	IDE_DIS_FINAL NUMERIC(18) NOT NULL,
	NOM_DIS_FINAL NVARCHAR(100) NOT NULL,
	DES_DIS_FINAL NVARCHAR(100),
	STA_DIS_FINAL NVARCHAR(2),
	IDE_USUARIO_CAMBIO NUMERIC(10),
	FEC_CAMBIO DATETIME2(6),
	NIV_LECTURA NUMERIC(1),
	NIV_ESCRITURA NUMERIC(1),
	IDE_UUID CHAR(32),
	FEC_CREACION DATETIME2(6)
)

ALTER TABLE ADM_DIS_FINAL ADD CONSTRAINT ADM_DIS_FINAL_PK
	PRIMARY KEY (IDE_DIS_FINAL)


  -------------------------------------------------------------------
  --Crear ADM_MOT_CREACION
  -------------------------------------------------------------------
  CREATE TABLE ADM_MOT_CREACION
( 
	IDE_MOT_CREACION NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_MOT_CREACION NVARCHAR(1020) NOT NULL
)

ALTER TABLE ADM_MOT_CREACION ADD CONSTRAINT MOCR_PK
	PRIMARY KEY (IDE_MOT_CREACION)


  
  -------------------------------------------------------------------
  --Crear ADM_SOPORTE
  -------------------------------------------------------------------
  CREATE TABLE ADM_SOPORTE
( 
	IDE_SOPORTE NUMERIC(19) NOT NULL,
	DES_SOPORTE NVARCHAR(1020) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_SOPORTE NVARCHAR(1020) NOT NULL
)

ALTER TABLE ADM_SOPORTE ADD CONSTRAINT SOPO_PK
	PRIMARY KEY (IDE_SOPORTE)

  
  -------------------------------------------------------------------
  --Crear ADM_CONFIG_INSTRUMENTO
  -------------------------------------------------------------------  
  CREATE TABLE ADM_CONFIG_INSTRUMENTO
( 
	IDE_INSTRUMENTO NVARCHAR(75) NOT NULL,
	EST_INSTRUMENTO NUMERIC DEFAULT 0
)

ALTER TABLE ADM_CONFIG_INSTRUMENTO ADD CONSTRAINT INES_PK
	PRIMARY KEY (IDE_INSTRUMENTO)



  -------------------------------------------------------------------
  --Crear ADM_SERIE
  -------------------------------------------------------------------  
  CREATE TABLE ADM_SERIE
( 
	IDE_SERIE NUMERIC(19) NOT NULL,
	ACT_ADMINISTRATIVO NVARCHAR(1020) NOT NULL,
	CAR_ADMINISTRATIVA NUMERIC(10),
	CAR_LEGAL NUMERIC(10),
	CAR_TECNICA NUMERIC(10),
	COD_SERIE NVARCHAR(1020) NOT NULL,
	EST_SERIE NUMERIC(5) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	FUE_BIBLIOGRAFICA NVARCHAR(1020),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_SERIE NVARCHAR(1020) NOT NULL,
	NOT_ALCANCE NVARCHAR(1200),
	IDE_MOT_CREACION NUMERIC(19) NOT NULL
)
ALTER TABLE ADM_SERIE ADD CONSTRAINT ADM_SERIE_PK
	PRIMARY KEY (IDE_SERIE);
	
ALTER TABLE ADM_SERIE ADD CONSTRAINT SERI_UK
	UNIQUE (COD_SERIE);


  -------------------------------------------------------------------
  --Crear ADM_SUBSERIE
  ------------------------------------------------------------------- 
  CREATE TABLE ADM_SUBSERIE
( 
	IDE_SUBSERIE NUMERIC(19) NOT NULL,
	ACT_ADMINISTRATIVO NVARCHAR(1020) NOT NULL,
	CAR_ADMINISTRATIVA NUMERIC(10),
	CAR_LEGAL NUMERIC(10),
	CAR_TECNICA NUMERIC(10),
	COD_SUBSERIE NVARCHAR(1020) NOT NULL,
	EST_SUBSERIE NUMERIC(5) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	FUE_BIBLIOGRAFICA NVARCHAR(1020),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_SUBSERIE NVARCHAR(1020) NOT NULL,
	NOT_ALCANCE NVARCHAR(1020),
	IDE_MOT_CREACION NUMERIC(19) NOT NULL,
	IDE_SERIE NUMERIC(19)
)

ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_PK
	PRIMARY KEY (IDE_SUBSERIE)

ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE)

ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_MOCR_FK
	FOREIGN KEY (IDE_MOT_CREACION)
		REFERENCES ADM_MOT_CREACION (IDE_MOT_CREACION)

CREATE INDEX X_SUBS_MOCR ON ADM_SUBSERIE
(
	IDE_MOT_CREACION
)

CREATE INDEX X_SUBS_SERI ON ADM_SUBSERIE
(
	IDE_SERIE
)
  
  -------------------------------------------------------------------
  --Crear ADM_CCD
  -------------------------------------------------------------------  
  CREATE TABLE ADM_CCD
( 
	IDE_CCD NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	IDE_OFC_PROD NVARCHAR(20) NOT NULL,
	IDE_SERIE NUMERIC(19) NOT NULL,
	IDE_SUBSERIE NUMERIC(19),
	IDE_UNI_AMT NVARCHAR(20) NOT NULL,
	EST_CCD NUMERIC(5),
	VAL_VERSION NVARCHAR(6)
)

ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_PK
	PRIMARY KEY (IDE_CCD)

ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE)

ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_SUBS_FK
	FOREIGN KEY (IDE_SUBSERIE)
		REFERENCES ADM_SUBSERIE (IDE_SUBSERIE)

CREATE INDEX X_CCDS_ORGA ON ADM_CCD
(
	IDE_OFC_PROD
)

CREATE INDEX X_CCDS_ORGA1 ON ADM_CCD
(
	IDE_UNI_AMT
)

CREATE INDEX X_CCDS_SERI ON ADM_CCD
(
	IDE_SERIE
)

CREATE INDEX X_CCDS_SUBS ON ADM_CCD
(
	IDE_SUBSERIE
)


  -------------------------------------------------------------------
  --Crear ADM_CONFIG_CCD
  -------------------------------------------------------------------
CREATE TABLE ADM_CONFIG_CCD
( 
	IDE_CCD NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	IDE_OFC_PROD NVARCHAR(20) NOT NULL,
	IDE_SERIE NUMERIC(19) NOT NULL,
	IDE_SUBSERIE NUMERIC(19),
	IDE_UNI_AMT NVARCHAR(20) NOT NULL,
	EST_CCD NUMERIC(5)
)

ALTER TABLE ADM_CONFIG_CCD ADD CONSTRAINT CONFIG_CCDS_PK
	PRIMARY KEY (IDE_CCD)

ALTER TABLE ADM_CONFIG_CCD ADD CONSTRAINT CONFIG_CCDS_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE)

CREATE INDEX CONFIG_X_CCDS_ORGA ON ADM_CONFIG_CCD
(
	IDE_OFC_PROD
)

CREATE INDEX CONFIG_X_CCDS_ORGA1 ON ADM_CONFIG_CCD
(
	IDE_UNI_AMT
)

CREATE INDEX CONFIG_X_CCDS_SERI ON ADM_CONFIG_CCD
(
	IDE_SERIE
)

CREATE INDEX CONFIG_X_CCDS_SUBS ON ADM_CONFIG_CCD
(
	IDE_SUBSERIE
)


  -------------------------------------------------------------------
  --Crear ADM_TRAD_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TRAD_DOC
( 
	IDE_TRAD_DOC NUMERIC(19) NOT NULL,
	DES_TRAD_DOC NVARCHAR(1020) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_TRAD_DOC NVARCHAR(1020) NOT NULL
);
ALTER TABLE ADM_TRAD_DOC ADD CONSTRAINT TRDO_PK1
	PRIMARY KEY (IDE_TRAD_DOC);

  -------------------------------------------------------------------
  --Crear ADM_TPG_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TPG_DOC
( 
	IDE_TPG_DOC NUMERIC(19) NOT NULL,
	CAR_ADMINISTRATIVA NUMERIC(10),
	CAR_LEGAL NUMERIC(10),
	CAR_TECNICA NUMERIC(10),
	COD_TPG_DOC NVARCHAR(1020),
	EST_TPG_DOC NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_TPG_DOC NVARCHAR(1020) NOT NULL,
	IDE_SOPORTE NUMERIC(19),
	IDE_TRA_DOCUMENTAL NUMERIC(19),
	NOT_ALCANCE NVARCHAR(1020),
	FUE_BIBLIOGRAFICA NVARCHAR(1020)
);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT TPDO_PK
	PRIMARY KEY (IDE_TPG_DOC);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT ADM_TPG_DOC_UK1
	UNIQUE (NOM_TPG_DOC, IDE_TPG_DOC);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT TPDO_SOPO_FK
	FOREIGN KEY (IDE_SOPORTE)
		REFERENCES ADM_SOPORTE (IDE_SOPORTE);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT ADM_TPG_DOC_FK1
	FOREIGN KEY (IDE_TRA_DOCUMENTAL)
		REFERENCES ADM_TRAD_DOC (IDE_TRAD_DOC);

  -------------------------------------------------------------------
  --Crear ADM_SER_SUBSER_TPG
  -------------------------------------------------------------------
  CREATE TABLE ADM_SER_SUBSER_TPG
( 
	IDE_SERIE NUMERIC(19) NOT NULL,
	IDE_TPG_DOC NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	IDE_SUBSERIE NUMERIC(19),
	IDE_REL_SST NUMERIC(19) NOT NULL
);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_PK
	PRIMARY KEY (IDE_REL_SST);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SUBS_FK
	FOREIGN KEY (IDE_SUBSERIE)
		REFERENCES ADM_SUBSERIE (IDE_SUBSERIE);
ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_TPDO_FK
	FOREIGN KEY (IDE_TPG_DOC)
		REFERENCES ADM_TPG_DOC (IDE_TPG_DOC);

  
  -------------------------------------------------------------------
  --Crear ADM_TAB_RET_DOC
  -------------------------------------------------------------------
CREATE TABLE ADM_TAB_RET_DOC
( 
	IDE_TAB_RET_DOC NUMERIC(19) NOT NULL,
	AC_TRD NUMERIC(19) NOT NULL,
	AG_TRD NUMERIC(19) NOT NULL,
	EST_TAB_RET_DOC NUMERIC(5),
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	PRO_TRD NVARCHAR(2000) NOT NULL,
	IDE_DIS_FINAL NUMERIC(19) NOT NULL,
	IDE_SERIE NUMERIC(19) NOT NULL,
	IDE_SUBSERIE NUMERIC(19),
	IDE_OFC_PROD NVARCHAR(20) NOT NULL,
	IDE_UNI_AMT NVARCHAR(20) NOT NULL
);
ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_PK
	PRIMARY KEY (IDE_TAB_RET_DOC);
ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_SERI_FK
	FOREIGN KEY (IDE_SERIE)
		REFERENCES ADM_SERIE (IDE_SERIE);
ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_SUBS_FK
	FOREIGN KEY (IDE_SUBSERIE)
		REFERENCES ADM_SUBSERIE (IDE_SUBSERIE);

  -------------------------------------------------------------------
  --Crear CM_CARGA_MASIVA
  -------------------------------------------------------------------
  
  CREATE TABLE CM_CARGA_MASIVA
( 
	ID NUMERIC NOT NULL,
	NOMBRE NVARCHAR(100),
	FECHA_CREACION DATETIME2(6),
	TOTAL_REGISTROS NUMERIC,
	ESTADO NVARCHAR(30),
	TOTAL_REGISTROS_EXITOSOS NUMERIC(4),
	TOTAL_REGISTROS_ERROR NUMERIC(4)
);
ALTER TABLE CM_CARGA_MASIVA ADD CONSTRAINT CM_CARGA_MASIVA_PK
	PRIMARY KEY (ID);

  
  -------------------------------------------------------------------
  --Crear CM_REGISTRO_CARGA_MASIVA
  -------------------------------------------------------------------
  CREATE TABLE CM_REGISTRO_CARGA_MASIVA
( 
	ID NUMERIC NOT NULL,
	CARGA_MASIVA_ID NUMERIC,
	CONTENIDO NVARCHAR(1000),
	ESTADO NVARCHAR(25),
	MENSAJES NVARCHAR(1000)
);
ALTER TABLE CM_REGISTRO_CARGA_MASIVA ADD CONSTRAINT CM_REGISTRO_CARGA_MASIVA_PK
	PRIMARY KEY (ID);
ALTER TABLE CM_REGISTRO_CARGA_MASIVA ADD CONSTRAINT SYS_C0011047
	FOREIGN KEY (CARGA_MASIVA_ID)
		REFERENCES CM_CARGA_MASIVA (ID);

   -------------------------------------------------------------------
  --Crear TVS_ORGANIGRAMA_ADMINISTRATIVO
  -------------------------------------------------------------------
  CREATE TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO
( 
	IDE_ORGA_ADMIN NUMERIC NOT NULL,
	COD_ORG NVARCHAR(255) NOT NULL,
	NOM_ORG NVARCHAR(100) NOT NULL,
	DESC_ORG NVARCHAR(500) NOT NULL,
	IND_ES_ACTIVO NVARCHAR(1) NOT NULL,
	IDE_DIRECCION NUMERIC,
	IDE_PLAN_RESPONSABLE NUMERIC(19),
	IDE_ORGA_ADMIN_PADRE NUMERIC,
	COD_NIVEL NVARCHAR(100),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CREO NUMERIC(10),
	IDE_USUARIO_CAMBIO NUMERIC(10) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	NIV_LECTURA NUMERIC(1),
	NIV_ESCRITURA NUMERIC(1),
	IDE_UUID CHAR(32),
	VAL_SISTEMA NVARCHAR(2),
	VAL_VERSION NVARCHAR(10)
);
ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO ADD CONSTRAINT TVS_ORGA_ADMI_PK
	PRIMARY KEY (IDE_ORGA_ADMIN);
ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO ADD CONSTRAINT TVS_ORGANIGRAMA_ADMINISTR_FK1
	FOREIGN KEY (IDE_ORGA_ADMIN_PADRE)
		REFERENCES TVS_ORGANIGRAMA_ADMINISTRATIVO (IDE_ORGA_ADMIN);

  
  -------------------------------------------------------------------
  --Crear TABLE_GENERATOR
  -------------------------------------------------------------------
  CREATE TABLE TABLE_GENERATOR
( 
	SEQ_NAME NVARCHAR(40) NOT NULL,
	SEQ_VALUE NUMERIC(15)
);
ALTER TABLE TABLE_GENERATOR ADD CONSTRAINT TABLE_GENERATOR_PK
	PRIMARY KEY (SEQ_NAME);

  
  --------------------------------------------------------
--  Crear ADM_TAB_RET_DOC_ORG
--------------------------------------------------------
  
  CREATE TABLE ADM_TAB_RET_DOC_ORG
( 
	IDE_OFC_PROD NVARCHAR(20) NOT NULL,
	IDE_UNI_AMT NVARCHAR(20) NOT NULL,
	IDE_TAB_RET_DOC_ORG NUMERIC(19) NOT NULL,
	IDE_TAB_RET_DOC NUMERIC(19) NOT NULL,
	AC_TRD NUMERIC(19) NOT NULL,
	AG_TRD NUMERIC(19) NOT NULL,
	PRO_TRD NVARCHAR(2000) NOT NULL,
	IDE_DIS_FINAL NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NUM_VERSION NUMERIC NOT NULL
);
ALTER TABLE ADM_TAB_RET_DOC_ORG ADD CONSTRAINT ADM_TAB_RET_DOC_ORG_PK
	PRIMARY KEY (IDE_TAB_RET_DOC_ORG);
ALTER TABLE ADM_TAB_RET_DOC_ORG ADD CONSTRAINT ADM_TAB_RET_DOC_ORG_FK1
	FOREIGN KEY (IDE_TAB_RET_DOC)
		REFERENCES ADM_TAB_RET_DOC (IDE_TAB_RET_DOC);

  
--------------------------------------------------------
--  Crear TVS_CONFIG_ORG_ADMINISTRATIVO
--------------------------------------------------------
CREATE TABLE TVS_CONFIG_ORG_ADMINISTRATIVO
( 
	IDE_ORGA_ADMIN NUMERIC NOT NULL,
	COD_ORG NVARCHAR(255) NOT NULL,
	NOM_ORG NVARCHAR(100) NOT NULL,
	DESC_ORG NVARCHAR(500) NOT NULL,
	IND_ES_ACTIVO NVARCHAR(1) NOT NULL,
	IDE_DIRECCION NUMERIC,
	IDE_PLAN_RESPONSABLE NUMERIC(19),
	IDE_ORGA_ADMIN_PADRE NUMERIC,
	COD_NIVEL NVARCHAR(100),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CREO NUMERIC(10),
	IDE_USUARIO_CAMBIO NUMERIC(10),
	FEC_CAMBIO DATETIME2(6),
	NIV_LECTURA NUMERIC(1),
	NIV_ESCRITURA NUMERIC(1),
	IDE_UUID CHAR(32),
	VAL_SISTEMA NVARCHAR(2)
);
ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT ORAD_CONFIG_COD_UK
	UNIQUE (COD_ORG);
ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT TVS_CONFIG_ORG_ADMINISTRA_UK1
	UNIQUE (NOM_ORG);
ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT TVS_CONFIG_ORGA_ADMI_PK
	PRIMARY KEY (IDE_ORGA_ADMIN);
ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT TVS_CONFIG_ORG_ADMINISTRA_FK1
	FOREIGN KEY (IDE_ORGA_ADMIN_PADRE)
		REFERENCES TVS_CONFIG_ORG_ADMINISTRATIVO (IDE_ORGA_ADMIN);
		
		  
--------------------------------------------------------
--  Crear ADM_VERSION_TRD
--------------------------------------------------------
		
CREATE TABLE ADM_VERSION_TRD 
(
  IDE_VERSION NUMERIC(18) NOT NULL 
, VAL_VERSION NVARCHAR(6) NOT NULL 
, FEC_VERSION DATE NOT NULL 
, IDE_USUARIO NUMERIC(18) 
, IDE_OFC_PROD NVARCHAR(20) NOT NULL 
, IDE_UNI_AMT NVARCHAR(20) NOT NULL 
, NUM_VERSION NUMERIC(18)
);


CREATE UNIQUE INDEX VETRD_PK ON ADM_VERSION_TRD (IDE_VERSION);

ALTER TABLE ADM_VERSION_TRD ADD CONSTRAINT VETRD_PK
	PRIMARY KEY (IDE_VERSION);
	
--------------------------------------------------------
--  Crear ADM_REL_EQ_ORIGEN
--------------------------------------------------------	
	
	CREATE TABLE ADM_REL_EQ_ORIGEN
(

   IDE_REL_ORIGEN NUMERIC(20)  NOT NULL,
   IDE_UNI_AMT NVARCHAR(20)  NOT NULL,
   IDE_OFC_PROD NVARCHAR(20)  NOT NULL,
   IDE_SERIE NUMERIC(19)  NULL,
   IDE_SUBSERIE NUMERIC(19)  NULL,
   FEC_CREACION DATETIME2(6)  NULL
)

ALTER TABLE ADM_REL_EQ_ORIGEN ADD CONSTRAINT ADM_REL_EQ_ORIGEN_PK1 PRIMARY KEY (IDE_REL_ORIGEN)
GO

ALTER TABLE ADM_REL_EQ_ORIGEN ADD CONSTRAINT ADM_REL_EQ_ORIGEN_FK1 FOREIGN KEY (IDE_SERIE) REFERENCES ADM_SERIE (IDE_SERIE)
GO
ALTER TABLE ADM_REL_EQ_ORIGEN ADD CONSTRAINT ADM_REL_EQ_ORIGEN_FK2 FOREIGN KEY (IDE_SUBSERIE) REFERENCES ADM_SUBSERIE (IDE_SUBSERIE)
GO


--------------------------------------------------------
--  Crear ADM_REL_EQ_DESTINO
--------------------------------------------------------	

CREATE TABLE ADM_REL_EQ_DESTINO
(

   IDE_REL_DESTINO NUMERIC(20)  NOT NULL,
   IDE_REL_ORIGEN NUMERIC(20)  NULL,
   IDE_UNI_AMT NVARCHAR(20)  NOT NULL,
   IDE_OFC_PROD NVARCHAR(20)  NOT NULL,
   IDE_SERIE NUMERIC(19)  NULL,
   IDE_SUBSERIE NUMERIC(19)  NULL,
   FEC_CREACION DATETIME2(6)  NULL
)

ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_PK1 PRIMARY KEY (IDE_REL_DESTINO)

ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK1 FOREIGN KEY (IDE_SERIE) REFERENCES ADM_SERIE (IDE_SERIE)
ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK2 FOREIGN KEY (IDE_SUBSERIE) REFERENCES ADM_SUBSERIE (IDE_SUBSERIE)
ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK3 FOREIGN KEY (IDE_REL_ORIGEN) REFERENCES ADM_REL_EQ_ORIGEN (IDE_REL_ORIGEN)

