USE docmanager
GO
ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO DROP CONSTRAINT TVS_ORGANIGRAMA_ADMINISTR_FK1
GO
ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO DROP CONSTRAINT TVS_CONFIG_ORG_ADMINISTRA_FK1
GO
ALTER TABLE CM_REGISTRO_CARGA_MASIVA DROP CONSTRAINT SYS_C0011047
GO
ALTER TABLE ADM_TPG_DOC DROP CONSTRAINT ADM_TPG_DOC_FK1
GO
ALTER TABLE ADM_TPG_DOC DROP CONSTRAINT TPDO_SOPO_FK
GO
ALTER TABLE ADM_SUBSERIE DROP CONSTRAINT SUBS_MOCR_FK
GO
ALTER TABLE ADM_SUBSERIE DROP CONSTRAINT SUBS_SERI_FK
GO
ALTER TABLE ADM_CONFIG_CCD DROP CONSTRAINT CONFIG_CCDS_SERI_FK
GO
ALTER TABLE ADM_CCD DROP CONSTRAINT CCDS_SERI_FK
GO
ALTER TABLE ADM_CCD DROP CONSTRAINT CCDS_SUBS_FK
GO
ALTER TABLE ADM_SER_SUBSER_TPG DROP CONSTRAINT SSTP_SERI_FK
GO
ALTER TABLE ADM_SER_SUBSER_TPG DROP CONSTRAINT SSTP_SUBS_FK
GO
ALTER TABLE ADM_SER_SUBSER_TPG DROP CONSTRAINT SSTP_TPDO_FK
GO
ALTER TABLE ADM_TAB_RET_DOC DROP CONSTRAINT TRDO_SERI_FK
GO
ALTER TABLE ADM_TAB_RET_DOC DROP CONSTRAINT TRDO_SUBS_FK
GO
ALTER TABLE ADM_TAB_RET_DOC_ORG DROP CONSTRAINT ADM_TAB_RET_DOC_ORG_FK1
GO
ALTER TABLE ADM_TAB_RET_DOC_ORG DROP CONSTRAINT ADM_TAB_RET_DOC_ORG_FK1
GO
DROP TABLE ADM_TAB_RET_DOC_ORG
GO
ALTER TABLE ADM_TAB_RET_DOC DROP CONSTRAINT TRDO_SERI_FK
GO
ALTER TABLE ADM_TAB_RET_DOC DROP CONSTRAINT TRDO_SUBS_FK
GO
DROP TABLE ADM_TAB_RET_DOC
GO
ALTER TABLE ADM_SER_SUBSER_TPG DROP CONSTRAINT SSTP_SERI_FK
GO
ALTER TABLE ADM_SER_SUBSER_TPG DROP CONSTRAINT SSTP_SUBS_FK
GO
ALTER TABLE ADM_SER_SUBSER_TPG DROP CONSTRAINT SSTP_TPDO_FK
GO
DROP TABLE ADM_SER_SUBSER_TPG
GO
ALTER TABLE ADM_CCD DROP CONSTRAINT CCDS_SERI_FK
GO
ALTER TABLE ADM_CCD DROP CONSTRAINT CCDS_SUBS_FK
GO
DROP TABLE ADM_CCD
GO
ALTER TABLE ADM_CONFIG_CCD DROP CONSTRAINT CONFIG_CCDS_SERI_FK
GO
DROP TABLE ADM_CONFIG_CCD
GO
ALTER TABLE ADM_SUBSERIE DROP CONSTRAINT SUBS_MOCR_FK
GO
ALTER TABLE ADM_SUBSERIE DROP CONSTRAINT SUBS_SERI_FK
GO
DROP TABLE ADM_SUBSERIE
GO
ALTER TABLE ADM_TPG_DOC DROP CONSTRAINT ADM_TPG_DOC_FK1
GO
ALTER TABLE ADM_TPG_DOC DROP CONSTRAINT TPDO_SOPO_FK
GO
DROP TABLE ADM_TPG_DOC
GO
ALTER TABLE CM_REGISTRO_CARGA_MASIVA DROP CONSTRAINT SYS_C0011047
GO
DROP TABLE CM_REGISTRO_CARGA_MASIVA
GO
DROP TABLE TABLE_GENERATOR
GO
ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO DROP CONSTRAINT TVS_CONFIG_ORG_ADMINISTRA_FK1
GO
DROP TABLE TVS_CONFIG_ORG_ADMINISTRATIVO
GO
ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO DROP CONSTRAINT TVS_ORGANIGRAMA_ADMINISTR_FK1
GO
DROP TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO
GO
DROP TABLE ADM_TRAD_DOC
GO
DROP TABLE CM_CARGA_MASIVA
GO
ALTER TABLE ADM_CONFIG_INSTRUMENTO DROP CONSTRAINT DF__ADM_CONFI__EST_I__0425A276
GO
DROP TABLE ADM_CONFIG_INSTRUMENTO
GO
DROP TABLE ADM_DIS_FINAL
GO
DROP TABLE ADM_MOT_CREACION
GO
DROP TABLE ADM_SERIE
GO
DROP TABLE ADM_SOPORTE
GO

DROP TABLE ADM_VERSION_TRD
GO