-------------------------------------------------------------------
  --Crear ADM_TPG_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TPG_DOC
( 
	IDE_TPG_DOC NUMERIC(19) NOT NULL,
	CAR_ADMINISTRATIVA NUMERIC(10),
	CAR_LEGAL NUMERIC(10),
	CAR_TECNICA NUMERIC(10, 0),
	COD_TPG_DOC NVARCHAR(1020),
	EST_TPG_DOC NUMERIC(19, 2) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_TPG_DOC NVARCHAR(1020) NOT NULL,
	IDE_SOPORTE NUMERIC(19),
	IDE_TRA_DOCUMENTAL NUMERIC(19),
	NOT_ALCANCE NVARCHAR(1020),
	FUE_BIBLIOGRAFICA NVARCHAR(1020)
);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT TPDO_PK
	PRIMARY KEY (IDE_TPG_DOC);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT ADM_TPG_DOC_UK1
	UNIQUE (NOM_TPG_DOC, IDE_TPG_DOC);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT TPDO_SOPO_FK
	FOREIGN KEY (IDE_SOPORTE)
		REFERENCES ADM_SOPORTE (IDE_SOPORTE);
ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT ADM_TPG_DOC_FK1
	FOREIGN KEY (IDE_TRA_DOCUMENTAL)
		REFERENCES ADM_TRAD_DOC (IDE_TRAD_DOC);
  
Insert into ADM_TRAD_DOC (IDE_TRAD_DOC,DES_TRAD_DOC,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_TRAD_DOC) values ('1','Original',null,'25/01/16',null,null,null,null,'Original');
Insert into ADM_TRAD_DOC (IDE_TRAD_DOC,DES_TRAD_DOC,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_TRAD_DOC) values ('2','Copia',null,'25/01/16',null,null,null,null,'Copia');

  