  -------------------------------------------------------------------
  --Crear ADM_TRAD_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TRAD_DOC
( 
	IDE_TRAD_DOC NUMERIC(19) NOT NULL,
	DES_TRAD_DOC NVARCHAR(1020) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NOM_TRAD_DOC NVARCHAR(1020) NOT NULL
);
ALTER TABLE ADM_TRAD_DOC ADD CONSTRAINT TRDO_PK1
	PRIMARY KEY (IDE_TRAD_DOC);
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_TPGDOC_SEQ','1');