 --------------------------------------------------------
--  Crear ADM_TAB_RET_DOC_ORG
--------------------------------------------------------
  
  CREATE TABLE ADM_TAB_RET_DOC_ORG
( 
	IDE_OFC_PROD NVARCHAR(20) NOT NULL,
	IDE_UNI_AMT NVARCHAR(20) NOT NULL,
	IDE_TAB_RET_DOC_ORG NUMERIC(19) NOT NULL,
	IDE_TAB_RET_DOC NUMERIC(19) NOT NULL,
	AC_TRD NUMERIC(19) NOT NULL,
	AG_TRD NUMERIC(19) NOT NULL,
	PRO_TRD NVARCHAR(2000) NOT NULL,
	IDE_DIS_FINAL NUMERIC(19) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CAMBIO NUMERIC(19),
	IDE_UUID NVARCHAR(1020),
	NIV_ESCRITURA NUMERIC(5),
	NIV_LECTURA NUMERIC(5),
	NUM_VERSION NUMERIC NOT NULL
);
ALTER TABLE ADM_TAB_RET_DOC_ORG ADD CONSTRAINT ADM_TAB_RET_DOC_ORG_PK
	PRIMARY KEY (IDE_TAB_RET_DOC_ORG);
ALTER TABLE ADM_TAB_RET_DOC_ORG ADD CONSTRAINT ADM_TAB_RET_DOC_ORG_FK1
	FOREIGN KEY (IDE_TAB_RET_DOC)
		REFERENCES ADM_TAB_RET_DOC (IDE_TAB_RET_DOC);

  
	Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_TAB_RET_DOC_ORG_SEQ', '1');

	  