  -------------------------------------------------------------------
  --Crear TVS_ORGANIGRAMA_ADMINISTRATIVO
  -------------------------------------------------------------------
  CREATE TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO
( 
	IDE_ORGA_ADMIN NUMERIC NOT NULL,
	COD_ORG NVARCHAR(255) NOT NULL,
	NOM_ORG NVARCHAR(100) NOT NULL,
	DESC_ORG NVARCHAR(500) NOT NULL,
	IND_ES_ACTIVO NVARCHAR(1) NOT NULL,
	IDE_DIRECCION NUMERIC,
	IDE_PLAN_RESPONSABLE NUMERIC(19),
	IDE_ORGA_ADMIN_PADRE NUMERIC,
	COD_NIVEL NVARCHAR(100),
	FEC_CREACION DATETIME2(6),
	IDE_USUARIO_CREO NUMERIC(10),
	IDE_USUARIO_CAMBIO NUMERIC(10) NOT NULL,
	FEC_CAMBIO DATETIME2(6),
	NIV_LECTURA NUMERIC(1),
	NIV_ESCRITURA NUMERIC(1),
	IDE_UUID CHAR(32),
	VAL_SISTEMA NVARCHAR(2),
	VAL_VERSION NVARCHAR(10)
);
ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO ADD CONSTRAINT TVS_ORGA_ADMI_PK
	PRIMARY KEY (IDE_ORGA_ADMIN);
ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO ADD CONSTRAINT TVS_ORGANIGRAMA_ADMINISTR_FK1
	FOREIGN KEY (IDE_ORGA_ADMIN_PADRE)
		REFERENCES TVS_ORGANIGRAMA_ADMINISTRATIVO (IDE_ORGA_ADMIN);


  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('TVS_ORGANIGRAMA_SEQ','1');