-------------------------------------------------------------------
  --Crear ADM_TAB_RET_DOC
  -------------------------------------------------------------------
CREATE TABLE ADM_TAB_RET_DOC
  (
    IDE_TAB_RET_DOC    NUMBER(19, 2) NOT NULL ,
    AC_TRD             NUMBER(19, 2) NOT NULL ,
    AG_TRD             NUMBER(19, 2) NOT NULL ,
    EST_TAB_RET_DOC    NUMBER(5, 0) ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    PRO_TRD            VARCHAR2(500 CHAR) NOT NULL ,
    IDE_DIS_FINAL      NUMBER(19, 2) NOT NULL ,
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    IDE_SUBSERIE       NUMBER(19, 2) ,
    IDE_OFC_PROD       VARCHAR2(20 BYTE) NOT NULL ,
    IDE_UNI_AMT        VARCHAR2(20 BYTE) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TRDO_PK ON ADM_TAB_RET_DOC
  (
    IDE_TAB_RET_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_TRDO_AMT ON ADM_TAB_RET_DOC
    (
      IDE_UNI_AMT ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TRDO_ORG_PROD ON ADM_TAB_RET_DOC
    (
      IDE_OFC_PROD ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TRDO_SERI ON ADM_TAB_RET_DOC
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TRDO_SUBS ON ADM_TAB_RET_DOC
    (
      IDE_SUBSERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_PK PRIMARY KEY ( IDE_TAB_RET_DOC ) USING INDEX TRDO_PK ENABLE;
  ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) DISABLE;
  ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_SUBS_FK FOREIGN KEY ( IDE_SUBSERIE ) REFERENCES ADM_SUBSERIE ( IDE_SUBSERIE ) DISABLE;
  COMMENT ON TABLE ADM_TAB_RET_DOC IS  'Tabla que almacena los valores de las Tablas de Retención Documental';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_TAB_RET_DOC IS  'Llave primaria: Id de la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.AC_TRD IS  'Hace referencia a la Retencion AC asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.AG_TRD IS  'Hace referencia a la Retencion AG asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.EST_TAB_RET_DOC IS  'Estado de la tabla de retención dcumental.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.PRO_TRD IS  'Hace referencia al procedimiento asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_DIS_FINAL IS  'Hace referencia al ide de disposicion final asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_SERIE IS  'Llave foranea: Id de la  Serie asociada';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_SUBSERIE IS   'Llave foranea: Id de la  Subserie asociada';
  
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_TAB_RET_DOC_SEQ', '1');