-------------------------------------------------------------------
  --Crear CM_CARGA_MASIVA
  -------------------------------------------------------------------
  
  CREATE TABLE CM_CARGA_MASIVA
  (
    ID                       NUMBER NOT NULL ,
    NOMBRE                   VARCHAR2(100 BYTE) ,
    FECHA_CREACION           TIMESTAMP ,
    TOTAL_REGISTROS          NUMBER ,
    ESTADO                   VARCHAR2(30 BYTE) ,
    TOTAL_REGISTROS_EXITOSOS NUMBER(4, 0) ,
    TOTAL_REGISTROS_ERROR    NUMBER(4, 0) ,
    CONSTRAINT CM_CARGA_MASIVA_PK PRIMARY KEY ( ID ) USING INDEX ( CREATE UNIQUE INDEX CM_CARGA_MASIVA_PK ON CM_CARGA_MASIVA (ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('CM_CARGA_MASIVA_SEQ','1');
  