-------------------------------------------------------------------
  --Crear TABLE_GENERATOR
  -------------------------------------------------------------------
  
  CREATE TABLE TABLE_GENERATOR
  (
    SEQ_NAME  VARCHAR2(40 BYTE) NOT NULL ,
    SEQ_VALUE NUMBER(15, 0)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TABLE_GENERATOR_PK ON TABLE_GENERATOR
  (
    SEQ_NAME ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE TABLE_GENERATOR ADD CONSTRAINT TABLE_GENERATOR_PK PRIMARY KEY ( SEQ_NAME ) USING INDEX TABLE_GENERATOR_PK ENABLE;

  