	-------------------------------------------------------------------
	-------------------------------------------------------------------
	--Crear ADM_DIS_FINAL
	-------------------------------------------------------------------
	
	
CREATE TABLE ADM_DIS_FINAL
  (
    IDE_DIS_FINAL      NUMBER NOT NULL ,
    NOM_DIS_FINAL      VARCHAR2(100 BYTE) NOT NULL ,
    DES_DIS_FINAL      VARCHAR2(100 BYTE) ,
    STA_DIS_FINAL      VARCHAR2(2 BYTE) ,
    IDE_USUARIO_CAMBIO NUMBER(10, 0) ,
    FEC_CAMBIO         DATE,
    NIV_LECTURA        NUMBER(1, 0) ,
    NIV_ESCRITURA      NUMBER(1, 0) ,
    IDE_UUID           CHAR(32 BYTE) ,
    FEC_CREACION       DATE
  );

	CREATE UNIQUE INDEX ADM_DIS_FINAL_PK ON ADM_DIS_FINAL
  (
    IDE_DIS_FINAL ASC
  );
  
  ALTER TABLE ADM_DIS_FINAL ADD CONSTRAINT ADM_DIS_FINAL_PK PRIMARY KEY ( IDE_DIS_FINAL ) USING INDEX ADM_DIS_FINAL_PK ENABLE;
  COMMENT ON COLUMN ADM_DIS_FINAL.STA_DIS_FINAL IS 'Estado de la dispocicion final';
  
  -------------------------------------------------------------------
  --Crear ADM_MOT_CREACION
  -------------------------------------------------------------------
  
  CREATE TABLE ADM_MOT_CREACION
    (
      IDE_MOT_CREACION   NUMBER(19, 2) NOT NULL ,
      FEC_CAMBIO         TIMESTAMP(6) ,
      FEC_CREACION       TIMESTAMP(6) ,
      IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
      IDE_UUID           VARCHAR2(255 CHAR) ,
      NIV_ESCRITURA      NUMBER(5, 0) ,
      NIV_LECTURA        NUMBER(5, 0) ,
      NOM_MOT_CREACION   VARCHAR2(255 CHAR) NOT NULL
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOCOMPRESS;
CREATE UNIQUE INDEX MOCR_PK ON ADM_MOT_CREACION
  (
    IDE_MOT_CREACION ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_MOT_CREACION ADD CONSTRAINT MOCR_PK PRIMARY KEY ( IDE_MOT_CREACION ) USING INDEX MOCR_PK ENABLE;
  COMMENT ON TABLE ADM_MOT_CREACION IS 'Tabla del Nomenclador Motivo de Creación';
  COMMENT ON COLUMN ADM_MOT_CREACION.FEC_CAMBIO IS 'Fecha de cambio.';
  COMMENT ON COLUMN ADM_MOT_CREACION.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_MOT_CREACION.IDE_USUARIO_CAMBIO IS 'Identificador del usuario que cambia.';
  COMMENT ON COLUMN ADM_MOT_CREACION.IDE_UUID IS 'Identificación UUID.';
  COMMENT ON COLUMN ADM_MOT_CREACION.NIV_ESCRITURA IS 'Nivel de escritura.';
  COMMENT ON COLUMN ADM_MOT_CREACION.NIV_LECTURA IS 'Nivel de lectura.';
  COMMENT ON COLUMN ADM_MOT_CREACION.NOM_MOT_CREACION IS 'Nombre del motivo de creación.';
  
  -------------------------------------------------------------------  
  --Crear ADM_SOPORTE
  -------------------------------------------------------------------
  
  
  CREATE TABLE ADM_SOPORTE
  (
    IDE_SOPORTE        NUMBER(19, 0) NOT NULL ,
    DES_SOPORTE        VARCHAR2(255 CHAR) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_SOPORTE        VARCHAR2(255 CHAR) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX SOPO_PK ON ADM_SOPORTE
  (
    IDE_SOPORTE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_SOPORTE ADD CONSTRAINT SOPO_PK PRIMARY KEY ( IDE_SOPORTE ) USING INDEX SOPO_PK ENABLE;
  COMMENT ON TABLE ADM_SOPORTE IS 'Tabla Soporte, contiene los soportes de las entidades'; 
  COMMENT ON COLUMN ADM_SOPORTE.IDE_SOPORTE IS  'Llave primaria: Id de la Tabla Soporte';
  COMMENT ON COLUMN ADM_SOPORTE.DES_SOPORTE IS  'Descripción del soporte.';
  COMMENT ON COLUMN ADM_SOPORTE.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SOPORTE.FEC_CREACION IS 'Fecha de creación.';
  COMMENT ON COLUMN ADM_SOPORTE.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_SOPORTE.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_SOPORTE.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SOPORTE.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SOPORTE.NOM_SOPORTE IS  'Hace referencia al nombre del soporte';
  
  -------------------------------------------------------------------
  --Crear ADM_CONFIG_INSTRUMENTO
  -------------------------------------------------------------------  
  
  
  CREATE TABLE ADM_CONFIG_INSTRUMENTO
  (
    IDE_INSTRUMENTO NVARCHAR2(25) NOT NULL ,
    EST_INSTRUMENTO NUMBER DEFAULT 0
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX INES_PK ON ADM_CONFIG_INSTRUMENTO
  (
    IDE_INSTRUMENTO ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_CONFIG_INSTRUMENTO ADD CONSTRAINT INES_PK PRIMARY KEY ( IDE_INSTRUMENTO ) USING INDEX INES_PK ENABLE;
  COMMENT ON COLUMN ADM_CONFIG_INSTRUMENTO.IDE_INSTRUMENTO IS   'Identificador del estado por instrumento';
  COMMENT ON COLUMN ADM_CONFIG_INSTRUMENTO.EST_INSTRUMENTO IS   'Estado, activo o inactivo.';

  -------------------------------------------------------------------
  --Crear ADM_SERIE
  -------------------------------------------------------------------  
  CREATE TABLE ADM_SERIE
  (
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    ACT_ADMINISTRATIVO VARCHAR2(255 CHAR) NOT NULL ,
    CAR_ADMINISTRATIVA NUMBER(10, 0) ,
    CAR_LEGAL          NUMBER(10, 0) ,
    CAR_TECNICA        NUMBER(10, 0) ,
    COD_SERIE          VARCHAR2(255 CHAR) NOT NULL ,
    EST_SERIE          NUMBER(5, 0) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    FUE_BIBLIOGRAFICA  VARCHAR2(255 CHAR) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_SERIE          VARCHAR2(255 CHAR) NOT NULL ,
    NOT_ALCANCE        VARCHAR2(300 CHAR) ,
    IDE_MOT_CREACION   NUMBER(19, 2) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX ADM_SERIE_PK ON ADM_SERIE
  (
    IDE_SERIE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
CREATE UNIQUE INDEX SERI_UK ON ADM_SERIE
  (
    COD_SERIE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_SERI_MOCR ON ADM_SERIE
    (
      IDE_MOT_CREACION ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_SERIE ADD CONSTRAINT ADM_SERIE_PK PRIMARY KEY ( IDE_SERIE ) USING INDEX ADM_SERIE_PK ENABLE;
  ALTER TABLE ADM_SERIE ADD CONSTRAINT SERI_UK UNIQUE ( COD_SERIE ) USING INDEX SERI_UK ENABLE;
  
  COMMENT ON COLUMN ADM_SERIE.ACT_ADMINISTRATIVO IS  'Hace referencia al acto administrativo';
  COMMENT ON COLUMN ADM_SERIE.CAR_LEGAL IS  'Hace referencia a la Característica Legal de la serie';
  COMMENT ON COLUMN ADM_SERIE.CAR_TECNICA IS  'Hace referencia a la Característica Técnica de la serie';
  COMMENT ON COLUMN ADM_SERIE.COD_SERIE IS   'Hace referencia a la código de la serie';
  COMMENT ON COLUMN ADM_SERIE.EST_SERIE IS  'Hace referencia al Estado de la serie';
  COMMENT ON COLUMN ADM_SERIE.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SERIE.FEC_CREACION IS   'Fecha de creación del registro';
  COMMENT ON COLUMN ADM_SERIE.IDE_USUARIO_CAMBIO IS   'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_SERIE.IDE_UUID IS   'Identificacion UUID.';
  COMMENT ON COLUMN ADM_SERIE.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SERIE.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SERIE.NOM_SERIE IS   'Hace referencia al Nombre de la serie';
  COMMENT ON COLUMN ADM_SERIE.NOT_ALCANCE IS   'Hace referencia a la Nota de Alcance de la serie';

  -------------------------------------------------------------------
  --Crear ADM_SUBSERIE
  ------------------------------------------------------------------- 
  
  CREATE TABLE ADM_SUBSERIE
  (
    IDE_SUBSERIE       NUMBER(19, 2) NOT NULL ,
    ACT_ADMINISTRATIVO VARCHAR2(255 CHAR) NOT NULL ,
    CAR_ADMINISTRATIVA NUMBER(10, 0) ,
    CAR_LEGAL          NUMBER(10, 0) ,
    CAR_TECNICA        NUMBER(10, 0) ,
    COD_SUBSERIE       VARCHAR2(255 CHAR) NOT NULL ,
    EST_SUBSERIE       NUMBER(5, 0) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    FUE_BIBLIOGRAFICA  VARCHAR2(255 CHAR) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_SUBSERIE       VARCHAR2(255 CHAR) NOT NULL ,
    NOT_ALCANCE        VARCHAR2(255 CHAR) ,
    IDE_MOT_CREACION   NUMBER(19, 2) NOT NULL ,
    IDE_SERIE          NUMBER(19, 2)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX SUBS_PK ON ADM_SUBSERIE
  (
    IDE_SUBSERIE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_SUBS_MOCR ON ADM_SUBSERIE
    (
      IDE_MOT_CREACION ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_SUBS_SERI ON ADM_SUBSERIE
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_PK PRIMARY KEY ( IDE_SUBSERIE ) USING INDEX SUBS_PK ENABLE;
  ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_MOCR_FK FOREIGN KEY ( IDE_MOT_CREACION ) REFERENCES ADM_MOT_CREACION ( IDE_MOT_CREACION ) ENABLE;
  ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) ENABLE;
  COMMENT ON COLUMN ADM_SUBSERIE.ACT_ADMINISTRATIVO IS  'Hace referencia al acto administrativo';
  COMMENT ON COLUMN ADM_SUBSERIE.CAR_ADMINISTRATIVA IS  'Característica administrativa de la subserie.';
  COMMENT ON COLUMN ADM_SUBSERIE.CAR_LEGAL IS  'Hace referencia a la Característica Legal de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.CAR_TECNICA IS  'Hace referencia a la Caracterástica Técnica de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.COD_SUBSERIE IS  'Hace referencia al código de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.EST_SUBSERIE IS   'Hace referencia al Estado de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.FEC_CAMBIO IS   'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SUBSERIE.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_SUBSERIE.FUE_BIBLIOGRAFICA IS  'Fuente bibliográfica.';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_SUBSERIE.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SUBSERIE.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SUBSERIE.NOM_SUBSERIE IS  'Hace referencia al Nombre de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.NOT_ALCANCE  IS  'Hace referencia a la Nota Alcance de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_MOT_CREACION IS  'Identificador del motivo de creación.';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_SERIE IS  'llave foránea: Id de la tabla Serie asociada';
  
  -------------------------------------------------------------------
  --Crear ADM_CCD
  -------------------------------------------------------------------  
  
  CREATE TABLE ADM_CCD
  (
    IDE_CCD            NUMBER(19, 2) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    IDE_OFC_PROD       VARCHAR2(20 BYTE) NOT NULL ,
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    IDE_SUBSERIE       NUMBER(19, 2) ,
    IDE_UNI_AMT        VARCHAR2(20 BYTE) NOT NULL ,
    EST_CCD            NUMBER(5, 0) ,
    VAL_VERSION        VARCHAR2(6 BYTE),
	VAL_VERSION_ORG    VARCHAR2(6 BYTE), 
	NUM_VERSION_ORG    NUMBER(16,0),
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX CCDS_PK ON ADM_CCD
  (
    IDE_CCD ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_CCDS_ORGA ON ADM_CCD
    (
      IDE_OFC_PROD ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_CCDS_ORGA1 ON ADM_CCD
    (
      IDE_UNI_AMT ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_CCDS_SERI ON ADM_CCD
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_CCDS_SUBS ON ADM_CCD
    (
      IDE_SUBSERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_PK PRIMARY KEY ( IDE_CCD ) USING INDEX CCDS_PK ENABLE;
  ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) DISABLE;
  ALTER TABLE ADM_CCD ADD CONSTRAINT CCDS_SUBS_FK FOREIGN KEY ( IDE_SUBSERIE ) REFERENCES ADM_SUBSERIE ( IDE_SUBSERIE ) DISABLE;
 
  COMMENT ON TABLE ADM_CCD IS  'Tabla que representa el Cuadro de Clasificación Documental';
  COMMENT ON COLUMN ADM_CCD.IDE_CCD IS  'Identificador del cuadro de clasificación documental.';
  COMMENT ON COLUMN ADM_CCD.FEC_CAMBIO IS  'Fecha de cambio';
  COMMENT ON COLUMN ADM_CCD.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_CCD.IDE_USUARIO_CAMBIO IS  'Identificador del usuario que cambia.';
  COMMENT ON COLUMN ADM_CCD.IDE_UUID IS  'Identificador universal.';
  COMMENT ON COLUMN ADM_CCD.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_CCD.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_CCD.IDE_OFC_PROD IS  'Identificador de la Oficina de producción.';
  COMMENT ON COLUMN ADM_CCD.IDE_SERIE IS  'Identificador de la serie.';
  COMMENT ON COLUMN ADM_CCD.IDE_SUBSERIE IS  'Identificador de la subserie.';
  COMMENT ON COLUMN ADM_CCD.IDE_UNI_AMT IS  'Identificador de la unidad de almacenamiento.';
  COMMENT ON COLUMN ADM_CCD.EST_CCD IS  'Estado del cuadro.';
  COMMENT ON COLUMN ADM_CCD.VAL_VERSION IS  'Contiene la version del registro';
  
  -------------------------------------------------------------------
  --Crear ADM_CONFIG_CCD
  -------------------------------------------------------------------
CREATE TABLE ADM_CONFIG_CCD
  (
    IDE_CCD            NUMBER(19, 2) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    IDE_OFC_PROD       VARCHAR2(20 BYTE) NOT NULL ,
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    IDE_SUBSERIE       NUMBER(19, 2) ,
    IDE_UNI_AMT        VARCHAR2(20 BYTE) NOT NULL ,
    EST_CCD            NUMBER(5, 0)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX CONFIG_CCDS_PK ON ADM_CONFIG_CCD
  (
    IDE_CCD ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX CONFIG_X_CCDS_ORGA ON ADM_CONFIG_CCD
    (
      IDE_OFC_PROD ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX CONFIG_X_CCDS_ORGA1 ON ADM_CONFIG_CCD
    (
      IDE_UNI_AMT ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX CONFIG_X_CCDS_SERI ON ADM_CONFIG_CCD
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX CONFIG_X_CCDS_SUBS ON ADM_CONFIG_CCD
    (
      IDE_SUBSERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_CONFIG_CCD ADD CONSTRAINT CONFIG_CCDS_PK PRIMARY KEY ( IDE_CCD ) USING INDEX CONFIG_CCDS_PK ENABLE;
  ALTER TABLE ADM_CONFIG_CCD ADD CONSTRAINT CONFIG_CCDS_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) DISABLE;
  COMMENT ON TABLE ADM_CONFIG_CCD IS  'Tabla que representa el Cuadro de Clasificación Documental';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_CCD IS  'Identificador del cuadro de clasificación documental.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.FEC_CAMBIO IS  'Fecha de cambio';
  COMMENT ON COLUMN ADM_CONFIG_CCD.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_USUARIO_CAMBIO IS  'Identificador del usuario que cambia.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_UUID IS  'Identificador universal.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_OFC_PROD IS  'Identificador de la Oficina de producción.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_SERIE IS  'Identificador de la serie.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_SUBSERIE IS  'Identificador de la subserie.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.IDE_UNI_AMT IS  'Identificador de la unidad de almacenamiento.';
  COMMENT ON COLUMN ADM_CONFIG_CCD.EST_CCD IS  'Estado del cuadro.';
  
  -------------------------------------------------------------------
  --Crear ADM_TRAD_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TRAD_DOC
  (
    IDE_TRAD_DOC       NUMBER(19, 2) NOT NULL ,
    DES_TRAD_DOC       VARCHAR2(255 CHAR) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_TRAD_DOC       VARCHAR2(255 CHAR) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TRDO_PK1 ON ADM_TRAD_DOC
  (
    IDE_TRAD_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_TRAD_DOC ADD CONSTRAINT TRDO_PK1 PRIMARY KEY ( IDE_TRAD_DOC ) USING INDEX TRDO_PK1 ENABLE;
  COMMENT ON TABLE ADM_TRAD_DOC IS  'Tabla que almacena el Nomenclador de Tradicion Documental';
  COMMENT ON COLUMN ADM_TRAD_DOC.IDE_TRAD_DOC IS  'Identificador de la tradición documental.';
  COMMENT ON COLUMN ADM_TRAD_DOC.DES_TRAD_DOC IS  'Descripción la tradición documental.';
  COMMENT ON COLUMN ADM_TRAD_DOC.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_TRAD_DOC.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_TRAD_DOC.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_TRAD_DOC.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_TRAD_DOC.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_TRAD_DOC.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_TRAD_DOC.NOM_TRAD_DOC IS  'Nombre de la tradición documental.';

  
  -------------------------------------------------------------------
  --Crear ADM_TPG_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TPG_DOC
  (
    IDE_TPG_DOC        NUMBER(19, 2) NOT NULL ,
    CAR_ADMINISTRATIVA NUMBER(10, 0) ,
    CAR_LEGAL          NUMBER(10, 0) ,
    CAR_TECNICA        NUMBER(10, 0) ,
    COD_TPG_DOC        VARCHAR2(255 CHAR) ,
    EST_TPG_DOC        NUMBER(19, 2) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_TPG_DOC        VARCHAR2(500 CHAR) NOT NULL ,
    IDE_SOPORTE        NUMBER(19, 0) ,
    IDE_TRA_DOCUMENTAL NUMBER(19, 2) ,
    NOT_ALCANCE        VARCHAR2(255 CHAR) ,
    FUE_BIBLIOGRAFICA  VARCHAR2(255 CHAR)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX ADM_TPG_DOC_UK1 ON ADM_TPG_DOC
  (
    NOM_TPG_DOC ASC, IDE_TPG_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
CREATE UNIQUE INDEX TIDO_UK ON ADM_TPG_DOC
  (
    COD_TPG_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
CREATE UNIQUE INDEX TPDO_PK ON ADM_TPG_DOC
  (
    IDE_TPG_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_TPDO_SOPO ON ADM_TPG_DOC
    (
      IDE_SOPORTE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TPDO_TRDO ON ADM_TPG_DOC
    (
      IDE_TRA_DOCUMENTAL ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT TPDO_PK PRIMARY KEY ( IDE_TPG_DOC ) USING INDEX TPDO_PK ENABLE;
  ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT ADM_TPG_DOC_UK1 UNIQUE ( NOM_TPG_DOC , IDE_TPG_DOC ) USING INDEX ADM_TPG_DOC_UK1 ENABLE;
  ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT ADM_TPG_DOC_FK1 FOREIGN KEY ( IDE_TRA_DOCUMENTAL ) REFERENCES ADM_TRAD_DOC ( IDE_TRAD_DOC ) ENABLE;
  ALTER TABLE ADM_TPG_DOC ADD CONSTRAINT TPDO_SOPO_FK FOREIGN KEY ( IDE_SOPORTE ) REFERENCES ADM_SOPORTE ( IDE_SOPORTE ) ENABLE;
  COMMENT ON TABLE ADM_TPG_DOC IS  'Tabla que almacena los Tipos Documentales';
  COMMENT ON COLUMN ADM_TPG_DOC.IDE_TPG_DOC IS  'Llave primaria: id de la tabla Tipologia Documental';
  COMMENT ON COLUMN ADM_TPG_DOC.CAR_ADMINISTRATIVA IS  'Característica adminstrativa.';
  COMMENT ON COLUMN ADM_TPG_DOC.CAR_LEGAL IS  'Hace referencia a la Caracteristica Legal de la tabla Tipologia Documental';
  COMMENT ON COLUMN ADM_TPG_DOC.CAR_TECNICA IS  'Hace referencia a la Caracteristica Tecnica de la tabla Tipologia Documental';
  COMMENT ON COLUMN ADM_TPG_DOC.COD_TPG_DOC IS  'Hace referencia al Codigo de la tabla Tipologia Documental';
  COMMENT ON COLUMN ADM_TPG_DOC.EST_TPG_DOC IS  'Hace referencia al Estado de la tabla Tipologia Documental';
  COMMENT ON COLUMN ADM_TPG_DOC.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_TPG_DOC.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_TPG_DOC.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_TPG_DOC.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_TPG_DOC.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_TPG_DOC.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_TPG_DOC.NOM_TPG_DOC IS  'Hace referencia al Nombre de la tabla Tipologia Documental';
  COMMENT ON COLUMN ADM_TPG_DOC.IDE_SOPORTE IS  'Llave foránea: Id de la tabla soporte asociada';
  COMMENT ON COLUMN ADM_TPG_DOC.IDE_TRA_DOCUMENTAL IS  'Identificador de la tradición documental.';
  COMMENT ON COLUMN ADM_TPG_DOC.NOT_ALCANCE IS  'Nota de alcance.';
  COMMENT ON COLUMN ADM_TPG_DOC.FUE_BIBLIOGRAFICA IS  'Fuente bibliográfica.';
  
  -------------------------------------------------------------------
  --Crear ADM_SER_SUBSER_TPG
  -------------------------------------------------------------------
  
  CREATE TABLE ADM_SER_SUBSER_TPG
  (
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    IDE_TPG_DOC        NUMBER(19, 2) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    IDE_SUBSERIE       NUMBER(19, 2) ,
    IDE_REL_SST        NUMBER(19, 2) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX SSTP_PK ON ADM_SER_SUBSER_TPG
  (
    IDE_REL_SST ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_SSTP_SERI ON ADM_SER_SUBSER_TPG
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_SSTP_SUBS ON ADM_SER_SUBSER_TPG
    (
      IDE_SUBSERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_SSTP_TPDO ON ADM_SER_SUBSER_TPG
    (
      IDE_TPG_DOC ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_PK PRIMARY KEY ( IDE_REL_SST ) USING INDEX SSTP_PK ENABLE;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) DISABLE;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SUBS_FK FOREIGN KEY ( IDE_SUBSERIE ) REFERENCES ADM_SUBSERIE ( IDE_SUBSERIE ) DISABLE;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_TPDO_FK FOREIGN KEY ( IDE_TPG_DOC ) REFERENCES ADM_TPG_DOC ( IDE_TPG_DOC ) DISABLE;
  COMMENT ON TABLE ADM_SER_SUBSER_TPG
IS
  'Tabla que relaciona las Series Subseries y Tipologias Documentales';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_SERIE IS  'Identificador de la serie.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_TPG_DOC IS  'Identificador de la tipología.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_USUARIO_CAMBIO IS  'Identificador del usuario que cambia.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_UUID IS  'Identificación UUID.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_SUBSERIE IS  'Identificador de la subserie.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_REL_SST IS  'Identificador de la relación serie, subserie, tipología.';
  
  -------------------------------------------------------------------
  --Crear ADM_TAB_RET_DOC
  -------------------------------------------------------------------
CREATE TABLE ADM_TAB_RET_DOC
  (
    IDE_TAB_RET_DOC    NUMBER(19, 2) NOT NULL ,
    AC_TRD             NUMBER(19, 2) NOT NULL ,
    AG_TRD             NUMBER(19, 2) NOT NULL ,
    EST_TAB_RET_DOC    NUMBER(5, 0) ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    PRO_TRD            VARCHAR2(500 CHAR) NOT NULL ,
    IDE_DIS_FINAL      NUMBER(19, 2) NOT NULL ,
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    IDE_SUBSERIE       NUMBER(19, 2) ,
    IDE_OFC_PROD       VARCHAR2(20 BYTE) NOT NULL ,
    IDE_UNI_AMT        VARCHAR2(20 BYTE) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TRDO_PK ON ADM_TAB_RET_DOC
  (
    IDE_TAB_RET_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_TRDO_AMT ON ADM_TAB_RET_DOC
    (
      IDE_UNI_AMT ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TRDO_ORG_PROD ON ADM_TAB_RET_DOC
    (
      IDE_OFC_PROD ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TRDO_SERI ON ADM_TAB_RET_DOC
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_TRDO_SUBS ON ADM_TAB_RET_DOC
    (
      IDE_SUBSERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_PK PRIMARY KEY ( IDE_TAB_RET_DOC ) USING INDEX TRDO_PK ENABLE;
  ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) DISABLE;
  ALTER TABLE ADM_TAB_RET_DOC ADD CONSTRAINT TRDO_SUBS_FK FOREIGN KEY ( IDE_SUBSERIE ) REFERENCES ADM_SUBSERIE ( IDE_SUBSERIE ) DISABLE;
  COMMENT ON TABLE ADM_TAB_RET_DOC IS  'Tabla que almacena los valores de las Tablas de Retención Documental';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_TAB_RET_DOC IS  'Llave primaria: Id de la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.AC_TRD IS  'Hace referencia a la Retencion AC asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.AG_TRD IS  'Hace referencia a la Retencion AG asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.EST_TAB_RET_DOC IS  'Estado de la tabla de retención dcumental.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.PRO_TRD IS  'Hace referencia al procedimiento asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_DIS_FINAL IS  'Hace referencia al ide de disposicion final asociada a la TRD';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_SERIE IS  'Llave foranea: Id de la  Serie asociada';
  COMMENT ON COLUMN ADM_TAB_RET_DOC.IDE_SUBSERIE IS   'Llave foranea: Id de la  Subserie asociada';
  
  -------------------------------------------------------------------
  --Crear CM_CARGA_MASIVA
  -------------------------------------------------------------------
  
  CREATE TABLE CM_CARGA_MASIVA
  (
    ID                       NUMBER NOT NULL ,
    NOMBRE                   VARCHAR2(100 BYTE) ,
    FECHA_CREACION           TIMESTAMP ,
    TOTAL_REGISTROS          NUMBER ,
    ESTADO                   VARCHAR2(30 BYTE) ,
    TOTAL_REGISTROS_EXITOSOS NUMBER(4, 0) ,
    TOTAL_REGISTROS_ERROR    NUMBER(4, 0) ,
    CONSTRAINT CM_CARGA_MASIVA_PK PRIMARY KEY ( ID ) USING INDEX ( CREATE UNIQUE INDEX CM_CARGA_MASIVA_PK ON CM_CARGA_MASIVA (ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
  -------------------------------------------------------------------
  --Crear CM_REGISTRO_CARGA_MASIVA
  -------------------------------------------------------------------
  CREATE TABLE CM_REGISTRO_CARGA_MASIVA
  (
    ID              NUMBER NOT NULL ,
    CARGA_MASIVA_ID NUMBER ,
    CONTENIDO       VARCHAR2(1000 BYTE) ,
    ESTADO          VARCHAR2(25 BYTE) ,
    MENSAJES        VARCHAR2(1000 BYTE) ,
    CONSTRAINT CM_REGISTRO_CARGA_MASIVA_PK PRIMARY KEY ( ID ) USING INDEX ( CREATE UNIQUE INDEX CM_REGISTRO_CARGA_MASIVA_PK ON CM_REGISTRO_CARGA_MASIVA (ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
ALTER TABLE CM_REGISTRO_CARGA_MASIVA ADD CONSTRAINT SYS_C0011047 FOREIGN KEY ( CARGA_MASIVA_ID ) REFERENCES CM_CARGA_MASIVA ( ID ) ENABLE;
  -------------------------------------------------------------------
  --Crear TVS_ORGANIGRAMA_ADMINISTRATIVO
  -------------------------------------------------------------------
  
  CREATE TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO
  (
    IDE_ORGA_ADMIN       NUMBER NOT NULL ,
    COD_ORG              VARCHAR2(255 BYTE) NOT NULL ,
    NOM_ORG              VARCHAR2(100 BYTE) NOT NULL ,
    DESC_ORG             VARCHAR2(500 BYTE) NOT NULL ,
    IND_ES_ACTIVO        VARCHAR2(1 BYTE) NOT NULL ,
    IDE_DIRECCION        NUMBER ,
    IDE_PLAN_RESPONSABLE NUMBER(19, 2) ,
    IDE_ORGA_ADMIN_PADRE NUMBER ,
    COD_NIVEL            VARCHAR2(100 BYTE) ,
    FEC_CREACION         DATE ,
    IDE_USUARIO_CREO     NUMBER(10, 0) ,
    IDE_USUARIO_CAMBIO   NUMBER(10, 0) NOT NULL ,
    FEC_CAMBIO           DATE ,
    NIV_LECTURA          NUMBER(1, 0) ,
    NIV_ESCRITURA        NUMBER(1, 0) ,
    IDE_UUID             CHAR(32 BYTE) ,
    VAL_SISTEMA          VARCHAR2(2 BYTE) ,
    VAL_VERSION          VARCHAR2(10 BYTE)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TVS_ORGA_ADMI_PK ON TVS_ORGANIGRAMA_ADMINISTRATIVO
  (
    IDE_ORGA_ADMIN ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO ADD CONSTRAINT TVS_ORGA_ADMI_PK PRIMARY KEY ( IDE_ORGA_ADMIN ) USING INDEX TVS_ORGA_ADMI_PK ENABLE;
  ALTER TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO ADD CONSTRAINT TVS_ORGANIGRAMA_ADMINISTR_FK1 FOREIGN KEY ( IDE_ORGA_ADMIN_PADRE ) REFERENCES TVS_ORGANIGRAMA_ADMINISTRATIVO ( IDE_ORGA_ADMIN ) ENABLE;
  COMMENT ON COLUMN TVS_ORGANIGRAMA_ADMINISTRATIVO.IDE_ORGA_ADMIN IS  'Identificador Consecutivo Registro';
  COMMENT ON COLUMN TVS_ORGANIGRAMA_ADMINISTRATIVO.COD_ORG IS  'Codigo de la unidad administrativa';
  COMMENT ON COLUMN TVS_ORGANIGRAMA_ADMINISTRATIVO.NOM_ORG IS  'Nombre de la unidad administrativa';
  COMMENT ON COLUMN TVS_ORGANIGRAMA_ADMINISTRATIVO.DESC_ORG IS  'Descripción de la unidad administrativa';
  COMMENT ON COLUMN TVS_ORGANIGRAMA_ADMINISTRATIVO.IND_ES_ACTIVO IS  'Estado de la unidad administrativa';

 
  -------------------------------------------------------------------
  --Crear TABLE_GENERATOR
  -------------------------------------------------------------------
  
  CREATE TABLE TABLE_GENERATOR
  (
    SEQ_NAME  VARCHAR2(40 BYTE) NOT NULL ,
    SEQ_VALUE NUMBER(15, 0)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TABLE_GENERATOR_PK ON TABLE_GENERATOR
  (
    SEQ_NAME ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE TABLE_GENERATOR ADD CONSTRAINT TABLE_GENERATOR_PK PRIMARY KEY ( SEQ_NAME ) USING INDEX TABLE_GENERATOR_PK ENABLE;

  
  -------------------------------------------------------------------
  --Crear ADM_TAB_RET_DOC_ORG
  --------------------------------------------------------

  CREATE TABLE "ADM_TAB_RET_DOC_ORG" 
   (	"IDE_OFC_PROD" VARCHAR2(20 BYTE), 
	"IDE_UNI_AMT" VARCHAR2(20 BYTE), 
	"IDE_TAB_RET_DOC_ORG" NUMBER(19,2), 
	"IDE_TAB_RET_DOC" NUMBER(19,2), 
	"AC_TRD" NUMBER(19,2), 
	"AG_TRD" NUMBER(19,2), 
	"PRO_TRD" VARCHAR2(500 CHAR), 
	"IDE_DIS_FINAL" NUMBER(19,2), 
	"FEC_CAMBIO" TIMESTAMP (6), 
	"FEC_CREACION" TIMESTAMP (6), 
	"IDE_USUARIO_CAMBIO" NUMBER(19,0), 
	"IDE_UUID" VARCHAR2(255 CHAR), 
	"NIV_ESCRITURA" NUMBER(5,0), 
	"NIV_LECTURA" NUMBER(5,0), 
	"NUM_VERSION" NUMBER
   );

   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_OFC_PROD" IS 'Identificador del organigrama, oficina productora';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_UNI_AMT" IS 'Identificador del organigrama, unidad administrativa';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_TAB_RET_DOC_ORG" IS 'Identificador de la tabla';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_TAB_RET_DOC" IS 'Identificador de la tabla de retencion documental';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."AC_TRD" IS 'Hace referencia a la Retencion AC asociada a la TRD';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."AG_TRD" IS 'Hace referencia a la Retencion AG asociada a la TRD';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."PRO_TRD" IS 'Hace referencia al procedimiento asociada a la TRD';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_DIS_FINAL" IS 'Hace referencia al ide de disposicion final asociada a la TRD';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."FEC_CAMBIO" IS 'Fecha de cambio.';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."FEC_CREACION" IS 'Fecha de creacion';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_USUARIO_CAMBIO" IS 'Identificador usuario que cambio.';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."IDE_UUID" IS 'Identificacion UUID.';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."NIV_ESCRITURA" IS 'Nivel de escritura.';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."NIV_LECTURA" IS 'Nivel de lectura.';
   COMMENT ON COLUMN "ADM_TAB_RET_DOC_ORG"."NUM_VERSION" IS 'Identificador del número de versión';



  CREATE UNIQUE INDEX "ADM_TAB_RET_DOC_ORG_PK" ON "ADM_TAB_RET_DOC_ORG" ("IDE_TAB_RET_DOC_ORG");


  ALTER TABLE "ADM_TAB_RET_DOC_ORG" ADD CONSTRAINT "ADM_TAB_RET_DOC_ORG_PK" PRIMARY KEY ("IDE_TAB_RET_DOC_ORG");
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("NUM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("IDE_DIS_FINAL" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("PRO_TRD" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("IDE_TAB_RET_DOC" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("AG_TRD" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("AC_TRD" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("IDE_TAB_RET_DOC_ORG" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("IDE_UNI_AMT" NOT NULL ENABLE);
  ALTER TABLE "ADM_TAB_RET_DOC_ORG" MODIFY ("IDE_OFC_PROD" NOT NULL ENABLE);

  ALTER TABLE "ADM_TAB_RET_DOC_ORG" ADD CONSTRAINT "ADM_TAB_RET_DOC_ORG_FK1" FOREIGN KEY ("IDE_TAB_RET_DOC")
	  REFERENCES "ADM_TAB_RET_DOC" ("IDE_TAB_RET_DOC") ENABLE;

  -------------------------------------------------------------------
  --Crear TVS_CONFIG_ORG_ADMINISTRATIVO
  --------------------------------------------------------

CREATE TABLE TVS_CONFIG_ORG_ADMINISTRATIVO
  (
    IDE_ORGA_ADMIN       NUMBER NOT NULL ,
    COD_ORG              VARCHAR2(255 BYTE) NOT NULL ,
    NOM_ORG              VARCHAR2(100 BYTE) NOT NULL ,
    DESC_ORG             VARCHAR2(500 BYTE) NOT NULL ,
    IND_ES_ACTIVO        VARCHAR2(1 BYTE) NOT NULL ,
    IDE_DIRECCION        NUMBER ,
    IDE_PLAN_RESPONSABLE NUMBER(19, 2) ,
    IDE_ORGA_ADMIN_PADRE NUMBER ,
    COD_NIVEL            VARCHAR2(100 BYTE) ,
    FEC_CREACION         DATE ,
    IDE_USUARIO_CREO     NUMBER(10, 0) ,
    IDE_USUARIO_CAMBIO   NUMBER(10, 0) ,
    FEC_CAMBIO           DATE ,
    NIV_LECTURA          NUMBER(1, 0) ,
    NIV_ESCRITURA        NUMBER(1, 0) ,
    IDE_UUID             CHAR(32 BYTE) ,
    VAL_SISTEMA          VARCHAR2(2 BYTE)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX ORAD_CONFIG_COD_UK ON TVS_CONFIG_ORG_ADMINISTRATIVO
  (
    COD_ORG ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
CREATE UNIQUE INDEX TVS_CONFIG_ORGA_ADMI_PK ON TVS_CONFIG_ORG_ADMINISTRATIVO
  (
    IDE_ORGA_ADMIN ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
CREATE UNIQUE INDEX TVS_CONFIG_ORG_ADMINISTRA_UK1 ON TVS_CONFIG_ORG_ADMINISTRATIVO
  (
    NOM_ORG ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT TVS_CONFIG_ORGA_ADMI_PK PRIMARY KEY ( IDE_ORGA_ADMIN ) USING INDEX TVS_CONFIG_ORGA_ADMI_PK ENABLE;
  ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT ORAD_CONFIG_COD_UK UNIQUE ( COD_ORG ) USING INDEX ORAD_CONFIG_COD_UK ENABLE;
  ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT TVS_CONFIG_ORG_ADMINISTRA_UK1 UNIQUE ( NOM_ORG ) USING INDEX TVS_CONFIG_ORG_ADMINISTRA_UK1 ENABLE;
  ALTER TABLE TVS_CONFIG_ORG_ADMINISTRATIVO ADD CONSTRAINT TVS_CONFIG_ORG_ADMINISTRA_FK1 FOREIGN KEY ( IDE_ORGA_ADMIN_PADRE ) REFERENCES TVS_CONFIG_ORG_ADMINISTRATIVO ( IDE_ORGA_ADMIN ) ENABLE;
  COMMENT ON COLUMN TVS_CONFIG_ORG_ADMINISTRATIVO.IDE_ORGA_ADMIN IS  'Identificador Consecutivo Registro';
  COMMENT ON COLUMN TVS_CONFIG_ORG_ADMINISTRATIVO.COD_ORG IS  'Codigo de la unidad administrativa';
  COMMENT ON COLUMN TVS_CONFIG_ORG_ADMINISTRATIVO.NOM_ORG IS  'Nombre de la unidad administrativa';
  COMMENT ON COLUMN TVS_CONFIG_ORG_ADMINISTRATIVO.DESC_ORG IS  'Descripción de la unidad administrativa';
  COMMENT ON COLUMN TVS_CONFIG_ORG_ADMINISTRATIVO.IND_ES_ACTIVO IS  'Estado de la unidad administrativa';
  
  -------------------------------------------------------------------
  --Crear ADM_VERSION_TRD
  --------------------------------------------------------

  CREATE TABLE "ADM_VERSION_TRD" 
   (	"IDE_VERSION" NUMBER(18,1), 
	"VAL_VERSION" VARCHAR2(6 BYTE), 
	"FEC_VERSION" DATE DEFAULT sysdate, 
	"IDE_USUARIO" NUMBER(18,1), 
	"IDE_OFC_PROD" VARCHAR2(20 BYTE), 
	"IDE_UNI_AMT" VARCHAR2(20 BYTE), 
	"NUM_VERSION" NUMBER(18,0)
   );

   COMMENT ON COLUMN "ADM_VERSION_TRD"."IDE_VERSION" IS 'Identificador de la versión.';
   COMMENT ON COLUMN "ADM_VERSION_TRD"."VAL_VERSION" IS 'valor de la versión.';
   COMMENT ON COLUMN "ADM_VERSION_TRD"."FEC_VERSION" IS 'Fecha de creación.';
   COMMENT ON COLUMN "ADM_VERSION_TRD"."IDE_USUARIO" IS 'Identificador del usuario.';
   COMMENT ON COLUMN "ADM_VERSION_TRD"."IDE_OFC_PROD" IS 'Identificador de la oficina productora.';
   COMMENT ON COLUMN "ADM_VERSION_TRD"."IDE_UNI_AMT" IS 'Identificador de la unidad administrativa.';
   COMMENT ON COLUMN "ADM_VERSION_TRD"."NUM_VERSION" IS 'Número de la versión.';
--------------------------------------------------------
--  DDL for Index VETRD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VETRD_PK" ON "ADM_VERSION_TRD" ("IDE_VERSION");
--------------------------------------------------------
--  Constraints for Table ADM_VERSION_TRD
--------------------------------------------------------

  ALTER TABLE "ADM_VERSION_TRD" MODIFY ("NUM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "ADM_VERSION_TRD" ADD CONSTRAINT "VETRD_PK" PRIMARY KEY ("IDE_VERSION");
  ALTER TABLE "ADM_VERSION_TRD" MODIFY ("IDE_UNI_AMT" NOT NULL ENABLE);
  ALTER TABLE "ADM_VERSION_TRD" MODIFY ("IDE_OFC_PROD" NOT NULL ENABLE);
  ALTER TABLE "ADM_VERSION_TRD" MODIFY ("FEC_VERSION" NOT NULL ENABLE);
  ALTER TABLE "ADM_VERSION_TRD" MODIFY ("VAL_VERSION" NOT NULL ENABLE);
  ALTER TABLE "ADM_VERSION_TRD" MODIFY ("IDE_VERSION" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  CREATE TABLE ADM_REL_EQ_DESTINO 
   (	IDE_REL_DESTINO NUMBER, 
	IDE_REL_ORIGEN NUMBER, 
	IDE_UNI_AMT VARCHAR2(20 BYTE), 
	IDE_OFC_PROD VARCHAR2(20 BYTE), 
	IDE_SERIE NUMBER, 
	IDE_SUBSERIE NUMBER, 
	FEC_CREACION DATE
   );
--------------------------------------------------------
--  DDL for Index ADM_REL_EQ_DESTINO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX ADM_REL_EQ_DESTINO_PK ON ADM_REL_EQ_DESTINO (IDE_REL_DESTINO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  Constraints for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_PK PRIMARY KEY (IDE_REL_DESTINO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_OFC_PROD NOT NULL ENABLE);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_UNI_AMT NOT NULL ENABLE);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_REL_DESTINO NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK1 FOREIGN KEY (IDE_SERIE)
	  REFERENCES ADM_SERIE (IDE_SERIE) ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK2 FOREIGN KEY (IDE_SUBSERIE)
	  REFERENCES ADM_SUBSERIE (IDE_SUBSERIE) ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK3 FOREIGN KEY (IDE_REL_ORIGEN)
	  REFERENCES ADM_REL_EQ_ORIGEN (IDE_REL_ORIGEN) ENABLE;

	  



--------------------------------------------------------
--  DDL for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  CREATE TABLE ADM_REL_EQ_DESTINO 
   (	IDE_REL_DESTINO NUMBER, 
	IDE_REL_ORIGEN NUMBER, 
	IDE_UNI_AMT VARCHAR2(20 BYTE), 
	IDE_OFC_PROD VARCHAR2(20 BYTE), 
	IDE_SERIE NUMBER, 
	IDE_SUBSERIE NUMBER, 
	FEC_CREACION DATE
   );
--------------------------------------------------------
--  DDL for Index ADM_REL_EQ_DESTINO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX ADM_REL_EQ_DESTINO_PK ON ADM_REL_EQ_DESTINO (IDE_REL_DESTINO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  Constraints for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_PK PRIMARY KEY (IDE_REL_DESTINO)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_OFC_PROD NOT NULL ENABLE);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_UNI_AMT NOT NULL ENABLE);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_REL_DESTINO NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK1 FOREIGN KEY (IDE_SERIE)
	  REFERENCES ADM_SERIE (IDE_SERIE) ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK2 FOREIGN KEY (IDE_SUBSERIE)
	  REFERENCES ADM_SUBSERIE (IDE_SUBSERIE) ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK3 FOREIGN KEY (IDE_REL_ORIGEN)
	  REFERENCES ADM_REL_EQ_ORIGEN (IDE_REL_ORIGEN) ENABLE;

	  



