-------------------------------------------------------------------
  --Crear ADM_SER_SUBSER_TPG
  -------------------------------------------------------------------
  
  CREATE TABLE ADM_SER_SUBSER_TPG
  (
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    IDE_TPG_DOC        NUMBER(19, 2) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    IDE_SUBSERIE       NUMBER(19, 2) ,
    IDE_REL_SST        NUMBER(19, 2) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX SSTP_PK ON ADM_SER_SUBSER_TPG
  (
    IDE_REL_SST ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_SSTP_SERI ON ADM_SER_SUBSER_TPG
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_SSTP_SUBS ON ADM_SER_SUBSER_TPG
    (
      IDE_SUBSERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_SSTP_TPDO ON ADM_SER_SUBSER_TPG
    (
      IDE_TPG_DOC ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_PK PRIMARY KEY ( IDE_REL_SST ) USING INDEX SSTP_PK ENABLE;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) DISABLE;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_SUBS_FK FOREIGN KEY ( IDE_SUBSERIE ) REFERENCES ADM_SUBSERIE ( IDE_SUBSERIE ) DISABLE;
  ALTER TABLE ADM_SER_SUBSER_TPG ADD CONSTRAINT SSTP_TPDO_FK FOREIGN KEY ( IDE_TPG_DOC ) REFERENCES ADM_TPG_DOC ( IDE_TPG_DOC ) DISABLE;
  COMMENT ON TABLE ADM_SER_SUBSER_TPG
IS
  'Tabla que relaciona las Series Subseries y Tipologias Documentales';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_SERIE IS  'Identificador de la serie.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_TPG_DOC IS  'Identificador de la tipología.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_USUARIO_CAMBIO IS  'Identificador del usuario que cambia.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_UUID IS  'Identificación UUID.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_SUBSERIE IS  'Identificador de la subserie.';
  COMMENT ON COLUMN ADM_SER_SUBSER_TPG.IDE_REL_SST IS  'Identificador de la relación serie, subserie, tipología.';
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_SER_SUBSER_TPG_SEQ','1');