--------------------------------------------------------
--  DDL for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  CREATE TABLE ADM_REL_EQ_DESTINO 
   (	IDE_REL_DESTINO NUMBER, 
	IDE_REL_ORIGEN NUMBER, 
	IDE_UNI_AMT VARCHAR2(20 BYTE), 
	IDE_OFC_PROD VARCHAR2(20 BYTE), 
	IDE_SERIE NUMBER, 
	IDE_SUBSERIE NUMBER, 
	FEC_CREACION DATE
   );
--------------------------------------------------------
--  DDL for Index ADM_REL_EQ_DESTINO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX ADM_REL_EQ_DESTINO_PK ON ADM_REL_EQ_DESTINO (IDE_REL_DESTINO);
--------------------------------------------------------
--  Constraints for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_PK PRIMARY KEY (IDE_REL_DESTINO);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_OFC_PROD NOT NULL ENABLE);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_UNI_AMT NOT NULL ENABLE);
  ALTER TABLE ADM_REL_EQ_DESTINO MODIFY (IDE_REL_DESTINO NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADM_REL_EQ_DESTINO
--------------------------------------------------------

  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK1 FOREIGN KEY (IDE_SERIE)
	  REFERENCES ADM_SERIE (IDE_SERIE) ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK2 FOREIGN KEY (IDE_SUBSERIE)
	  REFERENCES ADM_SUBSERIE (IDE_SUBSERIE) ENABLE;
  ALTER TABLE ADM_REL_EQ_DESTINO ADD CONSTRAINT ADM_REL_EQ_DESTINO_FK3 FOREIGN KEY (IDE_REL_ORIGEN)
	  REFERENCES ADM_REL_EQ_ORIGEN (IDE_REL_ORIGEN) ENABLE;

	  
	  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_REL_EQ_DES_SEQ','0');