-------------------------------------------------------------------  
  --Crear ADM_SOPORTE
  -------------------------------------------------------------------
  
  
  CREATE TABLE ADM_SOPORTE
  (
    IDE_SOPORTE        NUMBER(19, 0) NOT NULL ,
    DES_SOPORTE        VARCHAR2(255 CHAR) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_SOPORTE        VARCHAR2(255 CHAR) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX SOPO_PK ON ADM_SOPORTE
  (
    IDE_SOPORTE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_SOPORTE ADD CONSTRAINT SOPO_PK PRIMARY KEY ( IDE_SOPORTE ) USING INDEX SOPO_PK ENABLE;
  COMMENT ON TABLE ADM_SOPORTE IS 'Tabla Soporte, contiene los soportes de las entidades'; 
  COMMENT ON COLUMN ADM_SOPORTE.IDE_SOPORTE IS  'Llave primaria: Id de la Tabla Soporte';
  COMMENT ON COLUMN ADM_SOPORTE.DES_SOPORTE IS  'Descripción del soporte.';
  COMMENT ON COLUMN ADM_SOPORTE.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SOPORTE.FEC_CREACION IS 'Fecha de creación.';
  COMMENT ON COLUMN ADM_SOPORTE.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_SOPORTE.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_SOPORTE.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SOPORTE.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SOPORTE.NOM_SOPORTE IS  'Hace referencia al nombre del soporte';
  
	Insert into ADM_SOPORTE (IDE_SOPORTE,DES_SOPORTE,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_SOPORTE) values ('1','Soporte Físico',null,to_timestamp('25/01/16 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,'Físico');
	Insert into ADM_SOPORTE (IDE_SOPORTE,DES_SOPORTE,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_SOPORTE) values ('2','Soporte Electrónico',null,to_timestamp('25/01/16 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,'Electrónico');
	Insert into ADM_SOPORTE (IDE_SOPORTE,DES_SOPORTE,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_SOPORTE) values ('3','Soporte Híbrido',null,to_timestamp('25/01/16 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,'Físico y Electrónico');
