 -------------------------------------------------------------------
  --Crear CM_REGISTRO_CARGA_MASIVA
  -------------------------------------------------------------------
  CREATE TABLE CM_REGISTRO_CARGA_MASIVA
  (
    ID              NUMBER NOT NULL ,
    CARGA_MASIVA_ID NUMBER ,
    CONTENIDO       VARCHAR2(1000 BYTE) ,
    ESTADO          VARCHAR2(25 BYTE) ,
    MENSAJES        VARCHAR2(1000 BYTE) ,
    CONSTRAINT CM_REGISTRO_CARGA_MASIVA_PK PRIMARY KEY ( ID ) USING INDEX ( CREATE UNIQUE INDEX CM_REGISTRO_CARGA_MASIVA_PK ON CM_REGISTRO_CARGA_MASIVA (ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
ALTER TABLE CM_REGISTRO_CARGA_MASIVA ADD CONSTRAINT SYS_C0011047 FOREIGN KEY ( CARGA_MASIVA_ID ) REFERENCES CM_CARGA_MASIVA ( ID ) ENABLE;

Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('CM_REGISTRO_CARGA_MASIVA_SEQ','1');