-------------------------------------------------------------------
  --Crear ADM_CONFIG_INSTRUMENTO
  -------------------------------------------------------------------  
  
  
  CREATE TABLE ADM_CONFIG_INSTRUMENTO
  (
    IDE_INSTRUMENTO NVARCHAR2(25) NOT NULL ,
    EST_INSTRUMENTO NUMBER DEFAULT 0
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX INES_PK ON ADM_CONFIG_INSTRUMENTO
  (
    IDE_INSTRUMENTO ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_CONFIG_INSTRUMENTO ADD CONSTRAINT INES_PK PRIMARY KEY ( IDE_INSTRUMENTO ) USING INDEX INES_PK ENABLE;
  COMMENT ON COLUMN ADM_CONFIG_INSTRUMENTO.IDE_INSTRUMENTO IS   'Identificador del estado por instrumento';
  COMMENT ON COLUMN ADM_CONFIG_INSTRUMENTO.EST_INSTRUMENTO IS   'Estado, activo o inactivo.';
