-------------------------------------------------------------------
  --Crear ADM_SERIE
  -------------------------------------------------------------------  
  CREATE TABLE ADM_SERIE
  (
    IDE_SERIE          NUMBER(19, 2) NOT NULL ,
    ACT_ADMINISTRATIVO VARCHAR2(255 CHAR) NOT NULL ,
    CAR_ADMINISTRATIVA NUMBER(10, 0) ,
    CAR_LEGAL          NUMBER(10, 0) ,
    CAR_TECNICA        NUMBER(10, 0) ,
    COD_SERIE          VARCHAR2(255 CHAR) NOT NULL ,
    EST_SERIE          NUMBER(5, 0) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    FUE_BIBLIOGRAFICA  VARCHAR2(255 CHAR) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_SERIE          VARCHAR2(255 CHAR) NOT NULL ,
    NOT_ALCANCE        VARCHAR2(300 CHAR) ,
    IDE_MOT_CREACION   NUMBER(19, 2) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX ADM_SERIE_PK ON ADM_SERIE
  (
    IDE_SERIE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
CREATE UNIQUE INDEX SERI_UK ON ADM_SERIE
  (
    COD_SERIE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_SERI_MOCR ON ADM_SERIE
    (
      IDE_MOT_CREACION ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_SERIE ADD CONSTRAINT ADM_SERIE_PK PRIMARY KEY ( IDE_SERIE ) USING INDEX ADM_SERIE_PK ENABLE;
  ALTER TABLE ADM_SERIE ADD CONSTRAINT SERI_UK UNIQUE ( COD_SERIE ) USING INDEX SERI_UK ENABLE;
  
  COMMENT ON COLUMN ADM_SERIE.ACT_ADMINISTRATIVO IS  'Hace referencia al acto administrativo';
  COMMENT ON COLUMN ADM_SERIE.CAR_LEGAL IS  'Hace referencia a la Característica Legal de la serie';
  COMMENT ON COLUMN ADM_SERIE.CAR_TECNICA IS  'Hace referencia a la Característica Técnica de la serie';
  COMMENT ON COLUMN ADM_SERIE.COD_SERIE IS   'Hace referencia a la código de la serie';
  COMMENT ON COLUMN ADM_SERIE.EST_SERIE IS  'Hace referencia al Estado de la serie';
  COMMENT ON COLUMN ADM_SERIE.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SERIE.FEC_CREACION IS   'Fecha de creación del registro';
  COMMENT ON COLUMN ADM_SERIE.IDE_USUARIO_CAMBIO IS   'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_SERIE.IDE_UUID IS   'Identificacion UUID.';
  COMMENT ON COLUMN ADM_SERIE.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SERIE.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SERIE.NOM_SERIE IS   'Hace referencia al Nombre de la serie';
  COMMENT ON COLUMN ADM_SERIE.NOT_ALCANCE IS   'Hace referencia a la Nota de Alcance de la serie';
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_SERIE_SEQ','1');