-------------------------------------------------------------------
  --Crear ADM_TRAD_DOC
  -------------------------------------------------------------------
  CREATE TABLE ADM_TRAD_DOC
  (
    IDE_TRAD_DOC       NUMBER(19, 2) NOT NULL ,
    DES_TRAD_DOC       VARCHAR2(255 CHAR) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_TRAD_DOC       VARCHAR2(255 CHAR) NOT NULL
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX TRDO_PK1 ON ADM_TRAD_DOC
  (
    IDE_TRAD_DOC ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_TRAD_DOC ADD CONSTRAINT TRDO_PK1 PRIMARY KEY ( IDE_TRAD_DOC ) USING INDEX TRDO_PK1 ENABLE;
  COMMENT ON TABLE ADM_TRAD_DOC IS  'Tabla que almacena el Nomenclador de Tradicion Documental';
  COMMENT ON COLUMN ADM_TRAD_DOC.IDE_TRAD_DOC IS  'Identificador de la tradición documental.';
  COMMENT ON COLUMN ADM_TRAD_DOC.DES_TRAD_DOC IS  'Descripción la tradición documental.';
  COMMENT ON COLUMN ADM_TRAD_DOC.FEC_CAMBIO IS  'Fecha de cambio.';
  COMMENT ON COLUMN ADM_TRAD_DOC.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_TRAD_DOC.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_TRAD_DOC.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_TRAD_DOC.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_TRAD_DOC.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_TRAD_DOC.NOM_TRAD_DOC IS  'Nombre de la tradición documental.';
  
	Insert into ADM_TRAD_DOC (IDE_TRAD_DOC,DES_TRAD_DOC,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_TRAD_DOC) values ('1','Original',null,to_timestamp('25/01/16 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,'Original');
	Insert into ADM_TRAD_DOC (IDE_TRAD_DOC,DES_TRAD_DOC,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_TRAD_DOC) values ('2','Copia',null,to_timestamp('25/01/16 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,'Copia');

	
  