-------------------------------------------------------------------
  --Crear ADM_MOT_CREACION
  -------------------------------------------------------------------
  
  CREATE TABLE ADM_MOT_CREACION
    (
      IDE_MOT_CREACION   NUMBER(19, 2) NOT NULL ,
      FEC_CAMBIO         TIMESTAMP(6) ,
      FEC_CREACION       TIMESTAMP(6) ,
      IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
      IDE_UUID           VARCHAR2(255 CHAR) ,
      NIV_ESCRITURA      NUMBER(5, 0) ,
      NIV_LECTURA        NUMBER(5, 0) ,
      NOM_MOT_CREACION   VARCHAR2(255 CHAR) NOT NULL
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOCOMPRESS;
CREATE UNIQUE INDEX MOCR_PK ON ADM_MOT_CREACION
  (
    IDE_MOT_CREACION ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  ALTER TABLE ADM_MOT_CREACION ADD CONSTRAINT MOCR_PK PRIMARY KEY ( IDE_MOT_CREACION ) USING INDEX MOCR_PK ENABLE;
  COMMENT ON TABLE ADM_MOT_CREACION IS 'Tabla del Nomenclador Motivo de Creación';
  COMMENT ON COLUMN ADM_MOT_CREACION.FEC_CAMBIO IS 'Fecha de cambio.';
  COMMENT ON COLUMN ADM_MOT_CREACION.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_MOT_CREACION.IDE_USUARIO_CAMBIO IS 'Identificador del usuario que cambia.';
  COMMENT ON COLUMN ADM_MOT_CREACION.IDE_UUID IS 'Identificación UUID.';
  COMMENT ON COLUMN ADM_MOT_CREACION.NIV_ESCRITURA IS 'Nivel de escritura.';
  COMMENT ON COLUMN ADM_MOT_CREACION.NIV_LECTURA IS 'Nivel de lectura.';
  COMMENT ON COLUMN ADM_MOT_CREACION.NOM_MOT_CREACION IS 'Nombre del motivo de creación.';
  
  
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('1',to_timestamp('26/11/14 02:40:55,657000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null,'Nuevas Funciones');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('2',to_timestamp('26/11/14 02:41:20,991000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null,'Reestructuracion');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('3',to_timestamp('26/11/14 02:41:37,699000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null,'Fusion de Dependencias');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('4',to_timestamp('30/06/15 12:04:02,436000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null,'Cambio de Funciones entre Dependencias');
	Insert into ADM_MOT_CREACION (IDE_MOT_CREACION,FEC_CAMBIO,FEC_CREACION,IDE_USUARIO_CAMBIO,IDE_UUID,NIV_ESCRITURA,NIV_LECTURA,NOM_MOT_CREACION) values ('5',to_timestamp('26/11/14 02:42:11,972000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,null,null,null,null,'Normatividad');


  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_MOTIVODOC_SEQ','6');