-------------------------------------------------------------------
  --Crear ADM_SUBSERIE
  ------------------------------------------------------------------- 
  
  CREATE TABLE ADM_SUBSERIE
  (
    IDE_SUBSERIE       NUMBER(19, 2) NOT NULL ,
    ACT_ADMINISTRATIVO VARCHAR2(255 CHAR) NOT NULL ,
    CAR_ADMINISTRATIVA NUMBER(10, 0) ,
    CAR_LEGAL          NUMBER(10, 0) ,
    CAR_TECNICA        NUMBER(10, 0) ,
    COD_SUBSERIE       VARCHAR2(255 CHAR) NOT NULL ,
    EST_SUBSERIE       NUMBER(5, 0) NOT NULL ,
    FEC_CAMBIO         TIMESTAMP(6) ,
    FEC_CREACION       TIMESTAMP(6) ,
    FUE_BIBLIOGRAFICA  VARCHAR2(255 CHAR) ,
    IDE_USUARIO_CAMBIO NUMBER(19, 0) ,
    IDE_UUID           VARCHAR2(255 CHAR) ,
    NIV_ESCRITURA      NUMBER(5, 0) ,
    NIV_LECTURA        NUMBER(5, 0) ,
    NOM_SUBSERIE       VARCHAR2(255 CHAR) NOT NULL ,
    NOT_ALCANCE        VARCHAR2(255 CHAR) ,
    IDE_MOT_CREACION   NUMBER(19, 2) NOT NULL ,
    IDE_SERIE          NUMBER(19, 2)
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOCOMPRESS;
CREATE UNIQUE INDEX SUBS_PK ON ADM_SUBSERIE
  (
    IDE_SUBSERIE ASC
  )
  LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
  )
  NOPARALLEL;
  CREATE INDEX X_SUBS_MOCR ON ADM_SUBSERIE
    (
      IDE_MOT_CREACION ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  CREATE INDEX X_SUBS_SERI ON ADM_SUBSERIE
    (
      IDE_SERIE ASC
    )
    LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    )
    NOPARALLEL;
  ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_PK PRIMARY KEY ( IDE_SUBSERIE ) USING INDEX SUBS_PK ENABLE;
  ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_MOCR_FK FOREIGN KEY ( IDE_MOT_CREACION ) REFERENCES ADM_MOT_CREACION ( IDE_MOT_CREACION ) ENABLE;
  ALTER TABLE ADM_SUBSERIE ADD CONSTRAINT SUBS_SERI_FK FOREIGN KEY ( IDE_SERIE ) REFERENCES ADM_SERIE ( IDE_SERIE ) ENABLE;
  COMMENT ON COLUMN ADM_SUBSERIE.ACT_ADMINISTRATIVO IS  'Hace referencia al acto administrativo';
  COMMENT ON COLUMN ADM_SUBSERIE.CAR_ADMINISTRATIVA IS  'Característica administrativa de la subserie.';
  COMMENT ON COLUMN ADM_SUBSERIE.CAR_LEGAL IS  'Hace referencia a la Característica Legal de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.CAR_TECNICA IS  'Hace referencia a la Caracterástica Técnica de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.COD_SUBSERIE IS  'Hace referencia al código de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.EST_SUBSERIE IS   'Hace referencia al Estado de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.FEC_CAMBIO IS   'Fecha de cambio.';
  COMMENT ON COLUMN ADM_SUBSERIE.FEC_CREACION IS  'Fecha de creación.';
  COMMENT ON COLUMN ADM_SUBSERIE.FUE_BIBLIOGRAFICA IS  'Fuente bibliográfica.';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_USUARIO_CAMBIO IS  'Identificador usuario que cambio.';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_UUID IS  'Identificacion UUID.';
  COMMENT ON COLUMN ADM_SUBSERIE.NIV_ESCRITURA IS  'Nivel de escritura.';
  COMMENT ON COLUMN ADM_SUBSERIE.NIV_LECTURA IS  'Nivel de lectura.';
  COMMENT ON COLUMN ADM_SUBSERIE.NOM_SUBSERIE IS  'Hace referencia al Nombre de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.NOT_ALCANCE  IS  'Hace referencia a la Nota Alcance de la Subserie';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_MOT_CREACION IS  'Identificador del motivo de creación.';
  COMMENT ON COLUMN ADM_SUBSERIE.IDE_SERIE IS  'llave foránea: Id de la tabla Serie asociada';
  
  Insert into TABLE_GENERATOR (SEQ_NAME,SEQ_VALUE) values ('ADM_SUBSERIE_SEQ','1');