
package co.com.foundation.soaint.documentmanager.integration.client.ecm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ECMIntegrationServices", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ECMIntegrationServices {


    /**
     * 
     * @param password
     * @param estructura
     * @param user
     * @return
     *     returns co.com.foundation.soaint.documentmanager.integration.client.ecm.MessageResponse
     * @throws ECMIntegrationException_Exception
     */
    @WebMethod(action = "createStructureRecords")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createStructureRecords", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", className = "co.com.foundation.soaint.documentmanager.integration.client.ecm.CreateStructureRecords")
    @ResponseWrapper(localName = "createStructureRecordsResponse", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", className = "co.com.foundation.soaint.documentmanager.integration.client.ecm.CreateStructureRecordsResponse")
    public MessageResponse createStructureRecords(
        @WebParam(name = "estructura", targetNamespace = "")
        List<EstructuraTrdVO> estructura,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws ECMIntegrationException_Exception
    ;

    /**
     * 
     * @param password
     * @param estructura
     * @param user
     * @return
     *     returns co.com.foundation.soaint.documentmanager.integration.client.ecm.MessageResponse
     * @throws ECMIntegrationException_Exception
     */
    @WebMethod(action = "createStructureContent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createStructureContent", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", className = "co.com.foundation.soaint.documentmanager.integration.client.ecm.CreateStructureContent")
    @ResponseWrapper(localName = "createStructureContentResponse", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", className = "co.com.foundation.soaint.documentmanager.integration.client.ecm.CreateStructureContentResponse")
    public MessageResponse createStructureContent(
        @WebParam(name = "estructura", targetNamespace = "")
        List<EstructuraTrdVO> estructura,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws ECMIntegrationException_Exception
    ;

    /**
     * 
     * @param password
     * @param estructura
     * @param user
     * @return
     *     returns co.com.foundation.soaint.documentmanager.integration.client.ecm.MessageResponse
     * @throws ECMIntegrationException_Exception
     */
    @WebMethod(action = "createStructureECM")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createStructureECM", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", className = "co.com.foundation.soaint.documentmanager.integration.client.ecm.CreateStructureECM")
    @ResponseWrapper(localName = "createStructureECMResponse", targetNamespace = "http://co.com.soaint.sgd.correspondencia.service", className = "co.com.foundation.soaint.documentmanager.integration.client.ecm.CreateStructureECMResponse")
    public MessageResponse createStructureECM(
        @WebParam(name = "estructura", targetNamespace = "")
        List<EstructuraTrdVO> estructura)
        throws ECMIntegrationException_Exception
    ;

}
