
package co.com.foundation.soaint.documentmanager.integration.client.ecm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ECMIntegrationException", targetNamespace = "http://co.com.foundation.soaint.documentmanager.ws/services/records")
public class ECMIntegrationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ECMIntegrationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ECMIntegrationException_Exception(String message, ECMIntegrationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ECMIntegrationException_Exception(String message, ECMIntegrationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: co.com.foundation.soaint.documentmanager.integration.client.ecm.ECMIntegrationException
     */
    public ECMIntegrationException getFaultInfo() {
        return faultInfo;
    }

}
