CREATE TABLE SGDTEST.CM_CARGA_MASIVA
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(100),
    FECHA_CREACION TIMESTAMP(6),
    TOTAL_REGISTROS NUMBER(*),
    ESTADO VARCHAR2(30),
    TOTAL_REGISTROS_EXITOSOS NUMBER(4),
    TOTAL_REGISTROS_ERROR NUMBER(4)
);
INSERT INTO SGDTEST.CM_CARGA_MASIVA (ID, NOMBRE, FECHA_CREACION, TOTAL_REGISTROS, ESTADO, TOTAL_REGISTROS_EXITOSOS, TOTAL_REGISTROS_ERROR) VALUES (150, 'Plantilla Cargue Contigencia v1.0.xlsx', TO_TIMESTAMP('2018-04-12 13:58:34.424000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 2, 'COMPLETADO', 0, 2);
INSERT INTO SGDTEST.CM_CARGA_MASIVA (ID, NOMBRE, FECHA_CREACION, TOTAL_REGISTROS, ESTADO, TOTAL_REGISTROS_EXITOSOS, TOTAL_REGISTROS_ERROR) VALUES (151, 'Plantilla Cargue Contigencia v1.0.xlsx', TO_TIMESTAMP('2018-04-12 13:58:47.465000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 2, 'COMPLETADO', 0, 2);