CREATE TABLE SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK
(
    COD_ORGA_ADMI VARCHAR2(8) NOT NULL,
    IDE_FUNCI NUMBER(18) NOT NULL,
    ESTADO VARCHAR2(2),
    FEC_CAMBIO TIMESTAMP(6),
    FEC_CREACION TIMESTAMP(6),
    COD_USUARIO_CREA VARCHAR2(20),
    CONSTRAINT TVS_ORGA_ADMIN_X_FUNCI_PK_PK PRIMARY KEY (COD_ORGA_ADMI, IDE_FUNCI)
);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 1, 'I', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 18, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 18, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 18, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 19, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 19, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 19, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 20, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 20, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 20, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 21, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 21, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 21, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 22, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 22, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 22, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 23, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 23, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 23, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 1, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 3, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 4, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 5, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 3, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 4, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 5, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 3, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 4, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 5, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 6, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('200210', 6, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 6, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 15, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 15, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 17, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10001040', 2, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10001040', 16, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 1, 'A', null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 13, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 13, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 14, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401041', 14, null, null, null, null);
INSERT INTO SGDTEST.TVS_ORGA_ADMIN_X_FUNCI_PK (COD_ORGA_ADMI, IDE_FUNCI, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA) VALUES ('10401040', 2, 'A', null, null, null);