CREATE TABLE SGDTEST.TVS_PLANTILLA_METADATO
(
    IDE_PLANTILLA_METADATO NUMBER(18) PRIMARY KEY NOT NULL,
    COD_METADATO VARCHAR2(8),
    NOMB_METADATO VARCHAR2(50) NOT NULL,
    IDE_PLANTILLA NUMBER(18) NOT NULL,
    CONSTRAINT TVS_PLANT_MET_IDE_PLANT_FK FOREIGN KEY (IDE_PLANTILLA) REFERENCES TVS_PLANTILLA (IDE_PLANTILLA)
);
INSERT INTO SGDTEST.TVS_PLANTILLA_METADATO (IDE_PLANTILLA_METADATO, COD_METADATO, NOMB_METADATO, IDE_PLANTILLA) VALUES (1, 'NR', 'Nombre', 1);