CREATE TABLE SGDTEST.COR_PLANILLAS
(
    IDE_PLANILLA NUMBER(18) PRIMARY KEY NOT NULL,
    NRO_PLANILLA VARCHAR2(50) DEFAULT NULL
,
    FEC_GENERACION TIMESTAMP(6) DEFAULT NULL
,
    COD_TIPO_PLANILLA VARCHAR2(8) DEFAULT NULL
,
    COD_FUNC_GENERA VARCHAR2(8) DEFAULT NULL
,
    COD_SEDE_ORIGEN VARCHAR2(8) DEFAULT NULL
,
    COD_DEPENDENCIA_ORIGEN VARCHAR2(32) DEFAULT NULL
,
    COD_SEDE_DESTINO VARCHAR2(8) DEFAULT NULL
,
    COD_DEPENDENCIA_DESTINO VARCHAR2(8) DEFAULT NULL
,
    COD_CLASE_ENVIO VARCHAR2(8) DEFAULT NULL
,
    COD_MODALIDAD_ENVIO VARCHAR2(8) DEFAULT NULL
,
    FECHA_CREA TIMESTAMP(6) DEFAULT NULL
,
    COD_USUARIO_CREA VARCHAR2(20) DEFAULT NULL
,
    FECHA_MODIF TIMESTAMP(6) DEFAULT NULL
,
    COD_USUARIO_MODIF VARCHAR2(20) DEFAULT NULL
,
    IDE_ECM VARCHAR2(50)
);

INSERT INTO SGDTEST.COR_PLANILLAS (IDE_PLANILLA,NRO_PLANILLA,FEC_GENERACION,COD_TIPO_PLANILLA,COD_FUNC_GENERA,COD_SEDE_ORIGEN,COD_DEPENDENCIA_DESTINO,COD_CLASE_ENVIO,COD_MODALIDAD_ENVIO,FECHA_CREA,COD_USUARIO_CREA,FECHA_MODIF,COD_USUARIO_MODIF,IDE_ECM) VALUES ('IDE_PLANILLA1',00001,'NRO_PLANILLA1','FEC_GENERACION1','COD_TIPO_PLANILLA1','COD_FUNC_GENERA1','COD_SEDE_ORIGEN1','COD_DEPENDENCIA_DESTINO1','COD_CLASE_ENVIO1','COD_MODALIDAD_ENVIO1','FECHA_CREA1','COD_USUARIO_CREA1','FECHA_MODIF1','COD_USUARIO_MODIF1','IDE_ECM1');
INSERT INTO SGDTEST.COR_PLANILLAS (IDE_PLANILLA,NRO_PLANILLA,FEC_GENERACION,COD_TIPO_PLANILLA,COD_FUNC_GENERA,COD_SEDE_ORIGEN,COD_DEPENDENCIA_DESTINO,COD_CLASE_ENVIO,COD_MODALIDAD_ENVIO,FECHA_CREA,COD_USUARIO_CREA,FECHA_MODIF,COD_USUARIO_MODIF,IDE_ECM) VALUES ('IDE_PLANILLA2',00002,'NRO_PLANILLA2','FEC_GENERACION2','COD_TIPO_PLANILLA2','COD_FUNC_GENERA2','COD_SEDE_ORIGEN2','COD_DEPENDENCIA_DESTINO2','COD_CLASE_ENVIO2','COD_MODALIDAD_ENVIO2','FECHA_CREA2','COD_USUARIO_CREA1','FECHA_MODIF2','COD_USUARIO_MODIF1','IDE_ECM2');
