CREATE TABLE SGDTEST.TABLE_GENERATOR
(
    SEQ_NAME VARCHAR2(40) PRIMARY KEY NOT NULL,
    SEQ_VALUE NUMBER(15)
);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('TVS_ORGANIGRAMA_SEQ', 46);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('DCT_ASIGNACION_SEQ', 857);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('DCT_ASIG_ULTIMO_SEQ', 659);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('TVS_TAREA_SEQ', 122);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('FUNCIONARIOS_SEQ', 26);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('CM_CARGA_MASIVA_SEQ', 152);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('TVS_PLANTILLA_METADATO_SEQ', 0);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('COR_PLANILLAS_SEQ', 96);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('COR_PLAN_AGEN_SEQ', 117);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('TVS_PLANTILLA_SEQ', 0);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('COR_CORRESPONDENCIA_SEQ', 1335);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('COR_REFERIDO_SEQ', 277);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('PPD_DOCUMENTO_SEQ', 1333);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('COR_AGENTE_SEQ', 2689);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('COR_ANEXO_SEQ', 448);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('TVS_DATOS_CONTACTO_SEQ', 396);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('PPD_TRAZ_DOCUMENTO_SEQ', 320);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('CM_REGISTRO_CARGA_MASIVA_SEQ', 709);
INSERT INTO SGDTEST.TABLE_GENERATOR (SEQ_NAME, SEQ_VALUE) VALUES ('TVS_DSERIAL_SEQ', 690);