import {AfterViewInit, Component, Input, OnChanges, OnInit, SimpleChanges} from '@angular/core';
import {Guid} from "../../../infrastructure/utils/guid-generator";
import {isNullOrUndefined} from "util";

declare var PDFObject:any;

@Component({
  selector: 'app-pdf-viewer',
  templateUrl: './pdf-viewer.component.html',
  styleUrls: ['./pdf-viewer.component.css']
})

export class PdfViewerComponent implements OnChanges,AfterViewInit {

  @Input() pdfSrc;

  @Input() containerStyle:any = {};

  idAutoGenerated;

  constructor() {

    this.idAutoGenerated = `pdf-embeded-${Guid.next()}`;
  }


  ngOnChanges(changes: SimpleChanges): void {

    if(!isNullOrUndefined(this.pdfSrc) && !isNullOrUndefined(changes.pdfSrc))
      PDFObject.embed(this.pdfSrc,`#${this.idAutoGenerated}`)
  }

  ngAfterViewInit(): void {

    if(!isNullOrUndefined(this.pdfSrc))
     PDFObject.embed(this.pdfSrc,`#${this.idAutoGenerated}`)
  }

}
